/**
 * Advanced Substation Alpha export.
 *
 * `.srt` carries text and timing and nothing else, so handing one to an editor
 * throws away every styling decision made in this studio. ASS carries the font,
 * the size, the colours, the outline, the shadow, the alignment and the margins
 * - and, because this studio has per-word timings, real karaoke tags. Premiere,
 * Resolve, Final Cut, VLC, mpv, Aegisub and ffmpeg's `subtitles` filter all
 * read it, which makes it the format for "burn these somewhere else".
 */

import { CAPTION_FONTS, resolveFontWeight } from './fonts'
import type { CaptionCue, CaptionStyle } from './types'

export type AssPlan = {
	width: number
	height: number
}

/** ASS colours are &HAABBGGRR - alpha first, then blue, green, red. */
function assColor(input: string, alpha = 0): string {
	const value = input.trim()
	let r = 255
	let g = 255
	let b = 255
	let a = alpha

	const rgba = value.match(/rgba?\(\s*(\d+)[,\s]+(\d+)[,\s]+(\d+)(?:[,\s]+([\d.]+))?/i)
	if (rgba) {
		r = Number(rgba[1])
		g = Number(rgba[2])
		b = Number(rgba[3])
		if (rgba[4] !== undefined) a = Math.round((1 - Number(rgba[4])) * 255)
	} else if (value.startsWith('#')) {
		const hex = value.length === 4
			? value.slice(1).split('').map((character) => character + character).join('')
			: value.slice(1, 7)
		const int = Number.parseInt(hex, 16)
		r = (int >> 16) & 255
		g = (int >> 8) & 255
		b = int & 255
	}

	const pair = (channel: number) => channel.toString(16).padStart(2, '0').toUpperCase()
	return `&H${pair(a)}${pair(b)}${pair(g)}${pair(r)}`
}

/** ASS uses h:mm:ss.cc - centiseconds, and a single-digit hour. */
function assTime(ms: number): string {
	const clamped = Math.max(0, Math.round(ms))
	const centiseconds = Math.floor((clamped % 1000) / 10)
	const totalSeconds = Math.floor(clamped / 1000)
	const seconds = totalSeconds % 60
	const minutes = Math.floor(totalSeconds / 60) % 60
	const hours = Math.floor(totalSeconds / 3600)
	const pad = (value: number) => value.toString().padStart(2, '0')
	return `${hours}:${pad(minutes)}:${pad(seconds)}.${pad(centiseconds)}`
}

/** Numpad alignment: 1-3 bottom, 4-6 middle, 7-9 top. */
function assAlignment(style: CaptionStyle): number {
	const column = style.align === 'left' ? 1 : style.align === 'right' ? 3 : 2
	const row = style.placement === 'top' ? 6 : style.placement === 'center' ? 3 : 0
	return column + row
}

function applyCase(text: string, style: CaptionStyle): string {
	if (style.textCase === 'upper') return text.toUpperCase()
	if (style.textCase === 'lower') return text.toLowerCase()
	if (style.textCase === 'title') {
		return text.replace(/(^|\s)(\p{L})/gu, (_, lead, letter) => lead + letter.toUpperCase())
	}
	return text
}

function escapeAss(text: string): string {
	return text.replace(/\\/g, '\\\\').replace(/\{/g, '\\{').replace(/\}/g, '\\}').replace(/\n/g, '\\N')
}

/**
 * Builds the .ass file. Word timings become `\k` karaoke tags whenever the
 * studio is marking the spoken word, so the export animates the same way the
 * burned-in version does; a static look exports as plain styled dialogue.
 */
export function cuesToAss(cues: CaptionCue[], style: CaptionStyle, plan: AssPlan): string {
	const face = CAPTION_FONTS[style.fontId]
	const fontSize = Math.round((plan.height * style.fontSizePercent) / 100)
	const outline = Math.max(0, Math.round((fontSize * style.strokeWidth) / 100))
	const shadow = Math.round(style.shadow * fontSize * 0.06)
	const marginV = Math.round((plan.height * style.offsetPercent) / 100)
	const marginH = Math.round((plan.width * (100 - style.maxWidthPercent)) / 200)
	const bold = resolveFontWeight(style.fontId, style.fontWeight) >= 600 ? -1 : 0
	const karaoke = style.highlight !== 'none'

	const primary = assColor(style.fill === 'gradient' ? style.gradientFrom : style.textColor)
	const secondary = assColor(style.highlightColor)
	const outlineColor = assColor(style.strokeColor)
	const backColor = assColor(
		style.background === 'none' ? style.shadowColor : style.backgroundColor,
		style.background === 'none' ? 0 : Math.round((1 - style.backgroundOpacity) * 255),
	)

	const header = [
		'[Script Info]',
		'; Generated by the Remotion Video Studio subtitle tool.',
		'; Styling, margins and per-word karaoke timing all survive this export.',
		'ScriptType: v4.00+',
		`PlayResX: ${plan.width}`,
		`PlayResY: ${plan.height}`,
		'WrapStyle: 0',
		'ScaledBorderAndShadow: yes',
		'YCbCr Matrix: TV.709',
		'',
		'[V4+ Styles]',
		'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
		[
			'Style: Caption',
			face.family,
			fontSize,
			primary,
			secondary,
			outlineColor,
			backColor,
			bold,
			0,
			0,
			0,
			100,
			100,
			style.letterSpacing.toFixed(1),
			(-style.tilt).toFixed(1),
			style.background === 'none' ? 1 : 3,
			outline,
			shadow,
			assAlignment(style),
			marginH,
			marginH,
			marginV,
			1,
		].join(','),
		'',
		'[Events]',
		'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
	]

	const events = cues.map((cue) => {
		const body = karaoke
			? cue.tokens
					.map((token) => {
						// \k takes centiseconds of highlight time for the word that follows.
						const centiseconds = Math.max(1, Math.round((token.toMs - token.fromMs) / 10))
						return `{\\k${centiseconds}}${escapeAss(applyCase(token.text, style))}`
					})
					.join(' ')
			: escapeAss(applyCase(cue.text, style))

		return `Dialogue: 0,${assTime(cue.startMs)},${assTime(cue.endMs)},Caption,,0,0,0,,${body}`
	})

	return `${[...header, ...events].join('\n')}\n`
}
