/**
 * Writes the Remotion composition that burns the cues into the uploaded video.
 *
 * The studio compiles this exact text - preview, export and the .tsx you
 * download are the same program, so nothing can drift between what you see and
 * what you ship. Cues and styling are also handed to <Composition> as
 * defaultProps, which lets the editor re-style a caption without recompiling.
 */

import { CAPTION_FONTS } from './style-presets'
import type { CaptionCue, CaptionStyle } from './types'

export const CAPTION_ENTRY_FILE = 'captioned-video.tsx'

export type CompositionPlan = {
	id: string
	width: number
	height: number
	fps: number
	durationInFrames: number
}

export type CaptionSourceInput = {
	videoSrc: string
	videoName: string
	cues: CaptionCue[]
	style: CaptionStyle
	plan: CompositionPlan
	/** how the transcript was produced, written into the file header */
	origin: string
}

function jsonLiteral(value: unknown): string {
	return JSON.stringify(value, null, '\t')
}

function cueLiterals(cues: CaptionCue[]): string {
	if (cues.length === 0) return '[]'
	const rows = cues.map((cue) => {
		const tokens = cue.tokens
			.map((token) => JSON.stringify({ text: token.text, fromMs: token.fromMs, toMs: token.toMs }))
			.join(', ')
		return `\t{ id: ${JSON.stringify(cue.id)}, startMs: ${cue.startMs}, endMs: ${cue.endMs}, text: ${JSON.stringify(
			cue.text,
		)}, tokens: [${tokens}] },`
	})
	return `[\n${rows.join('\n')}\n]`
}

/** Builds the complete, self-contained .tsx for the captioned video. */
export function buildCaptionSource(input: CaptionSourceInput): string {
	const { videoSrc, videoName, cues, style, plan, origin } = input
	const font = CAPTION_FONTS[style.fontId]
	const words = cues.reduce((sum, cue) => sum + cue.tokens.length, 0)
	const seconds = (plan.durationInFrames / plan.fps).toFixed(1)

	return `/**
 * ${plan.id} - generated by the Remotion Video Studio subtitle tool.
 *
 * Source video : ${videoName}
 * Transcript   : ${origin}
 * Captions     : ${cues.length} cues, ${words} words
 * Timeline     : ${plan.width}x${plan.height}, ${plan.fps} fps, ${seconds}s
 *
 * The video address below is the one the studio used. A blob: address only
 * lives as long as the browser tab that created it, so replace VIDEO_SRC with a
 * public https:// URL or a staticFile('...') path before rendering this file
 * anywhere else (Remotion Studio, a CI render, the server engine).
 */

import {
	AbsoluteFill,
	Composition,
	Sequence,
	interpolate,
	registerRoot,
	spring,
	staticFile,
	useCurrentFrame,
	useVideoConfig,
} from 'remotion'
import { Video } from '@remotion/media'
import { loadFont } from '@remotion/fonts'

/* ------------------------------------------------------------------ data */

export const VIDEO_SRC = ${JSON.stringify(videoSrc)}

export const TIMELINE = ${jsonLiteral({
		id: plan.id,
		width: plan.width,
		height: plan.height,
		fps: plan.fps,
		durationInFrames: plan.durationInFrames,
	})}

export type CaptionToken = { text: string; fromMs: number; toMs: number }

export type CaptionCue = {
	id: string
	text: string
	startMs: number
	endMs: number
	tokens: CaptionToken[]
}

/** Edit the text or the timings here and the burned-in subtitles follow. */
export const CAPTIONS: CaptionCue[] = ${cueLiterals(cues)}

export const CAPTION_STYLE = ${jsonLiteral(style)}

export type CaptionStyle = typeof CAPTION_STYLE

/* ------------------------------------------------------------ typography */

// Self-hosted OFL font from the studio asset kit: loadFont() holds the render
// open until the face is parsed, so no frame is drawn in a fallback face.
loadFont({
	family: ${JSON.stringify(font.family)},
	url: staticFile(${JSON.stringify(`assets/fonts/v1/${font.file}`)}),
	weight: ${JSON.stringify(font.weight)},
})

const FONT_STACK = ${JSON.stringify(`'${font.family}', ${font.fallback}`)}

/* --------------------------------------------------------------- helpers */

const withAlpha = (color: string, alpha: number): string => {
	const hex = color.trim()
	if (!hex.startsWith('#')) return hex
	const value = hex.length === 4
		? hex.slice(1).split('').map((char) => char + char).join('')
		: hex.slice(1)
	const int = parseInt(value, 16)
	const r = (int >> 16) & 255
	const g = (int >> 8) & 255
	const b = int & 255
	return \`rgba(\${r}, \${g}, \${b}, \${alpha})\`
}

const justifyFor = (placement: string): 'flex-start' | 'center' | 'flex-end' => {
	if (placement === 'top') return 'flex-start'
	if (placement === 'center') return 'center'
	return 'flex-end'
}

/* ----------------------------------------------------------------- cue */

const CueLayer = ({ cue, captionStyle }: { cue: CaptionCue; captionStyle: CaptionStyle }) => {
	const frame = useCurrentFrame()
	const { fps, height } = useVideoConfig()

	// Inside a <Sequence> the frame is cue-relative, so the absolute media time
	// is the cue start plus however far we are into the cue.
	const timeMs = cue.startMs + (frame / fps) * 1000
	const cueFrames = Math.max(1, Math.round(((cue.endMs - cue.startMs) / 1000) * fps))

	const entrance = spring({
		frame,
		fps,
		config: { damping: 200, mass: 0.5, stiffness: 180 },
		durationInFrames: Math.min(9, cueFrames),
	})
	const exitFrom = Math.max(1, cueFrames - 4)
	const exitTo = Math.max(exitFrom + 1, cueFrames)
	const exit = interpolate(frame, [exitFrom, exitTo], [1, 0], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	})

	const animated = captionStyle.animation !== 'none'
	// The fade starts at 0.35 rather than 0: a caption that is fully transparent
	// on its own first frame reads as a flicker, and as a missing caption when
	// the preview is parked on that frame.
	const fadeIn = interpolate(frame, [0, Math.min(3, cueFrames)], [0.35, 1], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	})
	const opacity = animated ? Math.min(fadeIn, exit) : 1
	const scale = captionStyle.animation === 'pop' ? 0.82 + entrance * 0.18 : 1
	const translateY =
		captionStyle.animation === 'slide' ? (1 - entrance) * height * 0.045 : 0

	const fontSize = (height * captionStyle.fontSizePercent) / 100
	const strokeWidth = (fontSize * captionStyle.strokeWidth) / 100
	const dropShadow = captionStyle.shadow > 0
		? \`0 \${(fontSize * 0.05).toFixed(1)}px \${(fontSize * 0.22).toFixed(1)}px \${withAlpha(
				'#000000',
				captionStyle.shadow,
			)}\`
		: ''
	// The neon preset adds a coloured halo to the word being spoken.
	const glowShadow = captionStyle.preset === 'neon'
		? \`0 0 \${(fontSize * 0.38).toFixed(1)}px \${captionStyle.highlightColor}\`
		: ''

	return (
		<AbsoluteFill
			style={{
				display: 'flex',
				flexDirection: 'column',
				alignItems: 'center',
				justifyContent: justifyFor(captionStyle.placement),
				paddingTop:
					captionStyle.placement === 'top' ? (height * captionStyle.offsetPercent) / 100 : 0,
				paddingBottom:
					captionStyle.placement === 'bottom' ? (height * captionStyle.offsetPercent) / 100 : 0,
			}}
		>
			<div
				style={{
					display: 'flex',
					flexWrap: 'wrap',
					alignItems: 'center',
					justifyContent: 'center',
					maxWidth: \`\${captionStyle.maxWidthPercent}%\`,
					columnGap: fontSize * 0.24,
					rowGap: fontSize * (captionStyle.lineHeight - 1) + fontSize * 0.08,
					padding:
						captionStyle.background === 'none'
							? 0
							: \`\${fontSize * 0.26}px \${fontSize * 0.5}px\`,
					borderRadius:
						captionStyle.background === 'pill' ? fontSize * 1.2 : fontSize * 0.2,
					backgroundColor:
						captionStyle.background === 'none'
							? 'transparent'
							: withAlpha(captionStyle.backgroundColor, captionStyle.backgroundOpacity),
					opacity,
					transform: \`translateY(\${translateY.toFixed(2)}px) scale(\${scale.toFixed(3)})\`,
					fontFamily: FONT_STACK,
					fontWeight: captionStyle.fontWeight,
					fontSize,
					lineHeight: captionStyle.lineHeight,
					letterSpacing: captionStyle.letterSpacing,
					textTransform: captionStyle.uppercase ? 'uppercase' : 'none',
					textAlign: 'center',
				}}
			>
				{cue.tokens.map((token, index) => {
					const active = timeMs >= token.fromMs && timeMs < token.toMs
					const marked = active && captionStyle.highlight !== 'none'
					const boxed = marked && captionStyle.highlight === 'box'

					return (
						<span
							key={\`\${cue.id}-\${index}\`}
							style={{
								display: 'inline-block',
								color: boxed
									? captionStyle.highlightTextColor
									: marked
										? captionStyle.highlightColor
										: captionStyle.textColor,
								backgroundColor: boxed ? captionStyle.highlightColor : 'transparent',
								padding: boxed ? \`0 \${fontSize * 0.16}px\` : 0,
								borderRadius: fontSize * 0.16,
								transform:
									marked && captionStyle.highlight === 'scale'
										? \`scale(\${1 + 0.12 * entrance})\`
										: 'scale(1)',
								WebkitTextStroke:
									strokeWidth > 0 ? \`\${strokeWidth.toFixed(2)}px \${captionStyle.strokeColor}\` : undefined,
								paintOrder: 'stroke fill',
								textShadow:
									[marked ? glowShadow : '', dropShadow].filter(Boolean).join(', ') || 'none',
							}}
						>
							{token.text}
						</span>
					)
				})}
			</div>
		</AbsoluteFill>
	)
}

/* --------------------------------------------------------- composition */

export const CaptionedVideo = ({
	src = VIDEO_SRC,
	captions = CAPTIONS,
	captionStyle = CAPTION_STYLE,
}: {
	src?: string
	captions?: CaptionCue[]
	captionStyle?: CaptionStyle
}) => {
	const { fps } = useVideoConfig()

	return (
		<AbsoluteFill style={{ backgroundColor: '#000000' }}>
			<Video src={src} objectFit="cover" style={{ width: '100%', height: '100%' }} />
			{captions.map((cue) => {
				const from = Math.max(0, Math.round((cue.startMs / 1000) * fps))
				const durationInFrames = Math.max(
					1,
					Math.round((cue.endMs / 1000) * fps) - from,
				)
				return (
					<Sequence
						key={cue.id}
						from={from}
						durationInFrames={durationInFrames}
						name={cue.text.slice(0, 24)}
						layout="none"
					>
						<CueLayer cue={cue} captionStyle={captionStyle} />
					</Sequence>
				)
			})}
		</AbsoluteFill>
	)
}

const Root = () => (
	<>
		<Composition
			id={TIMELINE.id}
			component={CaptionedVideo}
			width={TIMELINE.width}
			height={TIMELINE.height}
			fps={TIMELINE.fps}
			durationInFrames={TIMELINE.durationInFrames}
			defaultProps={{ src: VIDEO_SRC, captions: CAPTIONS, captionStyle: CAPTION_STYLE }}
		/>
	</>
)

registerRoot(Root)

export default CaptionedVideo
`
}
