/**
 * Writes the Remotion composition that burns the cues into the uploaded video.
 *
 * The studio compiles this exact text - preview, export and the .tsx you
 * download are the same program, so nothing can drift between what you see and
 * what you ship. Cues and styling are also handed to <Composition> as
 * defaultProps, which lets the editor re-style a caption without recompiling.
 *
 * Everything the style engine can do is a pure function of the frame: gradient
 * fills, glows, faked 3D depth, the karaoke wipe, the per-word motion and the
 * typewriter reveal all read the clock and nothing else. No DOM measurement, no
 * randomness, so frame N is identical in the preview, in a browser export and
 * on a render farm.
 */

import { DEVANAGARI_FONTS, fontById, resolveFontWeight } from './fonts'
import type { CaptionCue, CaptionStyle } from './types'

export const CAPTION_ENTRY_FILE = 'captioned-video.tsx'

export type CompositionPlan = {
	id: string
	width: number
	height: number
	fps: number
	durationInFrames: number
}

export type CaptionSourceInput = {
	videoSrc: string
	videoName: string
	cues: CaptionCue[]
	style: CaptionStyle
	plan: CompositionPlan
	/** how the transcript was produced, written into the file header */
	origin: string
}

function jsonLiteral(value: unknown): string {
	return JSON.stringify(value, null, '\t')
}

function cueLiterals(cues: CaptionCue[]): string {
	if (cues.length === 0) return '[]'
	const rows = cues.map((cue) => {
		const tokens = cue.tokens
			.map((token) => JSON.stringify({ text: token.text, fromMs: token.fromMs, toMs: token.toMs }))
			.join(', ')
		return `\t{ id: ${JSON.stringify(cue.id)}, startMs: ${cue.startMs}, endMs: ${cue.endMs}, text: ${JSON.stringify(
			cue.text,
		)}, tokens: [${tokens}] },`
	})
	return `[\n${rows.join('\n')}\n]`
}

/** Builds the complete, self-contained .tsx for the captioned video. */
export function buildCaptionSource(input: CaptionSourceInput): string {
	const { videoSrc, videoName, cues, style, plan, origin } = input
	// fontById falls back to Inter rather than throwing: a style pasted from an
	// older studio version must still produce a renderable file.
	const font = fontById(style.fontId)
	const devanagari = style.devanagari
		? (DEVANAGARI_FONTS[style.devanagariFontId] ?? DEVANAGARI_FONTS.notoSansDevanagari)
		: null
	const words = cues.reduce((sum, cue) => sum + cue.tokens.length, 0)
	const seconds = (plan.durationInFrames / plan.fps).toFixed(1)

	// Latin face first, Devanagari companion second: CSS resolves the family per
	// character, so each script is drawn by the face that actually has it.
	const fontStack = [
		`'${font.family}'`,
		...(devanagari ? [`'${devanagari.family}'`] : []),
		font.fallback,
	].join(', ')

	/**
	 * A static face carries exactly one weight. Asking a browser for 700 on a
	 * 400-only file gets a synthesised bold that smears at caption size and
	 * differs between the preview and the render host, so the weight is pinned
	 * here and the slider is ignored for those families.
	 */
	const staticWeight = font.variable ? null : resolveFontWeight(style.fontId, style.fontWeight)

	const devanagariLoader = devanagari
		? `
// Devanagari companion - without it every Nepali glyph renders as a tofu box.
loadFont({
	family: ${JSON.stringify(devanagari.family)},
	url: staticFile(${JSON.stringify(`assets/fonts/v1/${devanagari.file}`)}),
	weight: ${JSON.stringify(devanagari.weight)},
})
`
		: ''

	return `/**
 * ${plan.id} - generated by the Remotion Video Studio subtitle tool.
 *
 * Source video : ${videoName}
 * Transcript   : ${origin}
 * Captions     : ${cues.length} cues, ${words} words
 * Timeline     : ${plan.width}x${plan.height}, ${plan.fps} fps, ${seconds}s
 * Type         : ${font.family}${devanagari ? ` + ${devanagari.family} for Devanagari` : ''}
 *
 * How it renders
 *   - every word carries its own timestamp, so the word being spoken can be
 *     marked, filled left to right, or animated on its own
 *   - lines are broken by linear partitioning, which balances a caption across
 *     up to \`maxLines\` rows instead of leaving an orphan word
 *   - fills, glows, the faked 3D edge and the per-word motion are all computed
 *     from the frame number, so nothing drifts between preview and render
 *   - an optional gradient scrim fades in under the caption zone, which is what
 *     keeps white type legible over bright or busy footage
 *
 * The video address below is the one the studio used. A blob: address only
 * lives as long as the browser tab that created it, so replace VIDEO_SRC with a
 * public https:// URL or a staticFile('...') path before rendering this file
 * anywhere else (Remotion Studio, a CI render, the server engine).
 */

import {
	AbsoluteFill,
	Composition,
	Sequence,
	interpolate,
	registerRoot,
	spring,
	staticFile,
	useCurrentFrame,
	useVideoConfig,
} from 'remotion'
import { useMemo } from 'react'
import { Video } from '@remotion/media'
import { loadFont } from '@remotion/fonts'

/* ------------------------------------------------------------------ data */

export const VIDEO_SRC = ${JSON.stringify(videoSrc)}

export const TIMELINE = ${jsonLiteral({
		id: plan.id,
		width: plan.width,
		height: plan.height,
		fps: plan.fps,
		durationInFrames: plan.durationInFrames,
	})}

export type CaptionToken = { text: string; fromMs: number; toMs: number }

export type CaptionCue = {
	id: string
	text: string
	startMs: number
	endMs: number
	tokens: CaptionToken[]
}

/** Edit the text or the timings here and the burned-in subtitles follow. */
export const CAPTIONS: CaptionCue[] = ${cueLiterals(cues)}

export const CAPTION_STYLE = ${jsonLiteral(style)}

export type CaptionStyle = typeof CAPTION_STYLE

/* ------------------------------------------------------------ typography */

// Self-hosted open-licence font from the studio asset kit: loadFont() holds the
// render open until the face is parsed, so no frame is drawn in a fallback face.
loadFont({
	family: ${JSON.stringify(font.family)},
	url: staticFile(${JSON.stringify(`assets/fonts/v1/${font.file}`)}),
	weight: ${JSON.stringify(font.weight)},
})
${devanagariLoader}
const FONT_STACK = ${JSON.stringify(fontStack)}

/** null for a variable face, which honours whatever weight the style asks for. */
const FONT_STATIC_WEIGHT: number | null = ${staticWeight === null ? 'null' : staticWeight}

/* --------------------------------------------------------------- helpers */

const withAlpha = (color: string, alpha: number): string => {
	const hex = color.trim()
	if (!hex.startsWith('#')) return hex
	const value = hex.length === 4
		? hex.slice(1).split('').map((char) => char + char).join('')
		: hex.slice(1)
	const int = parseInt(value, 16)
	const r = (int >> 16) & 255
	const g = (int >> 8) & 255
	const b = int & 255
	return \`rgba(\${r}, \${g}, \${b}, \${alpha})\`
}

const clamp01 = (value: number): number => Math.max(0, Math.min(1, value))

const justifyFor = (placement: string): 'flex-start' | 'center' | 'flex-end' => {
	if (placement === 'top') return 'flex-start'
	if (placement === 'center') return 'center'
	return 'flex-end'
}

const alignFor = (align: string): 'flex-start' | 'center' | 'flex-end' => {
	if (align === 'left') return 'flex-start'
	if (align === 'right') return 'flex-end'
	return 'center'
}

const caseFor = (textCase: string): 'uppercase' | 'lowercase' | 'capitalize' | 'none' => {
	if (textCase === 'upper') return 'uppercase'
	if (textCase === 'lower') return 'lowercase'
	if (textCase === 'title') return 'capitalize'
	return 'none'
}

/**
 * Deterministic pseudo-noise. The jitter effect needs a value that looks random
 * but is a pure function of (frame, word) - Math.random() would make every
 * render of the same frame different, which is the one thing a video pipeline
 * cannot tolerate.
 */
const noise = (a: number, b: number): number => {
	const value = Math.sin(a * 12.9898 + b * 78.233) * 43758.5453
	return value - Math.floor(value)
}

/**
 * Devanagari matras, anusvara, virama and the joiners stack on the consonant
 * they belong to instead of taking their own horizontal room. Counting them
 * would tell the line breaker that "छेउ" is as wide as a five letter English
 * word and leave Nepali rows half empty.
 */
const DEVANAGARI_COMBINING = /[\\u0900-\\u0902\\u093A-\\u094F\\u0951-\\u0957\\u0962\\u0963\\u200C\\u200D]/g

const wordWidth = (text: string): number => text.replace(DEVANAGARI_COMBINING, '').length

/** Emphasis matching ignores case and the punctuation stuck to a word. */
const bareWord = (text: string): string =>
	text.toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu, '')

/**
 * Balanced line breaking.
 *
 * Plain wrapping fills the first row and drops whatever is left onto the
 * second, which is how captions end up as five words above one lonely word.
 * This binary-searches the narrowest "widest row" that still fits the caption
 * in \`maxLines\`, then packs greedily at that width - the classic linear
 * partition, and the same thing a typesetter does by eye.
 */
const balanceLines = (tokens: CaptionToken[], maxLines: number): CaptionToken[][] => {
	const limit = Math.max(1, Math.min(4, Math.round(maxLines)))
	if (limit === 1 || tokens.length < 2) return [tokens]

	const widths = tokens.map((token) => wordWidth(token.text))

	const pack = (maxWidth: number): CaptionToken[][] | null => {
		const lines: CaptionToken[][] = []
		let current: CaptionToken[] = []
		let used = 0
		for (let index = 0; index < tokens.length; index++) {
			const cost = widths[index] + (current.length > 0 ? 1 : 0)
			if (current.length > 0 && used + cost > maxWidth) {
				lines.push(current)
				current = []
				used = 0
			}
			used += widths[index] + (current.length > 0 ? 1 : 0)
			current.push(tokens[index])
		}
		if (current.length > 0) lines.push(current)
		return lines.length <= limit ? lines : null
	}

	let low = Math.max(...widths)
	let high = widths.reduce((sum, width) => sum + width + 1, 0)
	let best = pack(high) ?? [tokens]
	while (low <= high) {
		const middle = Math.floor((low + high) / 2)
		const attempt = pack(middle)
		if (attempt) {
			best = attempt
			high = middle - 1
		} else {
			low = middle + 1
		}
	}
	return best
}

/* ----------------------------------------------------------------- scrim */

/**
 * A gradient wash under the caption zone. It fades in with the captions rather
 * than sitting on the footage the whole time, and it is what makes white type
 * survive a bright sky or a busy background.
 */
const CaptionScrim = ({
	captions,
	captionStyle,
}: {
	captions: CaptionCue[]
	captionStyle: CaptionStyle
}) => {
	const frame = useCurrentFrame()
	const { fps } = useVideoConfig()
	const timeMs = (frame / fps) * 1000

	let distance = 100000
	for (const cue of captions) {
		const gap = timeMs < cue.startMs
			? cue.startMs - timeMs
			: timeMs > cue.endMs
				? timeMs - cue.endMs
				: 0
		if (gap < distance) distance = gap
		if (distance === 0) break
	}

	const opacity = interpolate(distance, [0, 260], [1, 0], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	})
	if (opacity <= 0) return null

	const strength = captionStyle.scrim
	const soft = withAlpha('#000000', strength * 0.72)
	const full = withAlpha('#000000', strength)
	const clear = 'rgba(0, 0, 0, 0)'
	const gradient =
		captionStyle.placement === 'center'
			? \`linear-gradient(to top, \${clear} 16%, \${full} 42%, \${full} 58%, \${clear} 84%)\`
			: \`linear-gradient(to \${
					captionStyle.placement === 'top' ? 'bottom' : 'top'
				}, \${full} 0%, \${soft} 18%, \${clear} 48%)\`

	return <AbsoluteFill style={{ background: gradient, opacity }} />
}

/* ------------------------------------------------------------------ word */

type WordMetrics = {
	fontSize: number
	strokeWidth: number
	dropShadow: string
	extrudeShadow: string
	glowShadow: string
	activeGlowShadow: string
}

const CaptionWord = ({
	token,
	cueStartMs,
	timeMs,
	lineEntrance,
	captionStyle,
	metrics,
	index,
	typed,
}: {
	token: CaptionToken
	cueStartMs: number
	timeMs: number
	lineEntrance: number
	captionStyle: CaptionStyle
	metrics: WordMetrics
	/** position of the word in its line, used to phase the wave effect */
	index: number
	/** typewriter reveal: 0 - 1 of this word's characters, or null when off */
	typed: number | null
}) => {
	const frame = useCurrentFrame()
	const { fps } = useVideoConfig()

	// Word reveal: each word arrives on its own timestamp while the row keeps its
	// full layout, so the line never re-centres itself mid-sentence.
	const byWord = captionStyle.reveal === 'word'
	const startFrame = Math.round(((token.fromMs - cueStartMs) / 1000) * fps)
	const wordFrame = frame - startFrame
	const entrance = byWord
		? wordFrame < 0
			? 0
			: spring({
					frame: wordFrame,
					fps,
					config: { damping: 200, mass: 0.4, stiffness: 220 },
					durationInFrames: 7,
				})
		: lineEntrance

	const active = timeMs >= token.fromMs && timeMs < token.toMs
	const marked = active && captionStyle.highlight !== 'none'
	const boxed = marked && captionStyle.highlight === 'box'
	const popped = marked && captionStyle.highlight === 'scale'
	const emphasised =
		captionStyle.emphasisWords.length > 0 &&
		captionStyle.emphasisWords.includes(bareWord(token.text))

	/* ------------------------------------------------------------- motion */

	const seconds = Math.max(0, wordFrame) / fps
	const effect = active ? captionStyle.wordEffect : 'none'
	let effectY = 0
	let effectX = 0
	let effectScale = 1
	let effectRotate = 0

	if (effect === 'bounce') {
		effectY = -Math.abs(Math.sin(seconds * 9)) * metrics.fontSize * 0.12
	} else if (effect === 'wave') {
		effectY = Math.sin(seconds * 6 + index * 0.7) * metrics.fontSize * 0.07
	} else if (effect === 'pulse') {
		effectScale = 1 + Math.sin(seconds * 11) * 0.045
	} else if (effect === 'jitter') {
		effectX = (noise(frame, index) - 0.5) * metrics.fontSize * 0.06
		effectY = (noise(frame + 37, index) - 0.5) * metrics.fontSize * 0.06
	} else if (effect === 'flip') {
		effectRotate = interpolate(wordFrame, [0, 6], [82, 0], {
			extrapolateLeft: 'clamp',
			extrapolateRight: 'clamp',
		})
	}

	const scale = (byWord ? 0.86 + entrance * 0.14 : 1) * (popped ? 1.11 : 1) * effectScale
	const rise = byWord ? (1 - entrance) * metrics.fontSize * 0.28 : 0

	/* --------------------------------------------------------------- fill */

	const baseColor = emphasised ? captionStyle.emphasisColor : captionStyle.textColor
	const gradientFill = \`linear-gradient(\${captionStyle.gradientAngle}deg, \${captionStyle.gradientFrom}, \${captionStyle.gradientTo})\`

	// A karaoke wipe fills the spoken word left to right over its own span,
	// instead of switching colour on a single frame.
	const wipe = captionStyle.karaokeFill && active && captionStyle.highlight !== 'none'
	const wipeProgress = wipe
		? clamp01((timeMs - token.fromMs) / Math.max(1, token.toMs - token.fromMs))
		: 0

	const clipToText = {
		WebkitBackgroundClip: 'text' as const,
		backgroundClip: 'text' as const,
		color: 'transparent',
	}

	const fill = boxed
		? { color: captionStyle.highlightTextColor }
		: wipe
			? {
					backgroundImage: \`linear-gradient(90deg, \${captionStyle.highlightColor} \${(
						wipeProgress * 100
					).toFixed(2)}%, \${baseColor} \${(wipeProgress * 100).toFixed(2)}%)\`,
					...clipToText,
				}
			: marked
				? { color: captionStyle.highlightColor }
				: emphasised
					? { color: captionStyle.emphasisColor }
					: captionStyle.fill === 'gradient'
						? { backgroundImage: gradientFill, ...clipToText }
						: { color: baseColor }

	const shadow = [
		metrics.extrudeShadow,
		marked || emphasised ? metrics.activeGlowShadow : metrics.glowShadow,
		metrics.dropShadow,
	]
		.filter(Boolean)
		.join(', ')

	/* ---------------------------------------------------------- typewriter */

	const characters = Array.from(token.text)
	const shownCount = typed === null ? characters.length : Math.round(typed * characters.length)
	const shown = typed === null ? token.text : characters.slice(0, shownCount).join('')
	// The untyped tail is rendered transparent rather than removed, so the line
	// keeps its final width from frame one and never reflows as it types.
	const hidden = typed === null ? '' : characters.slice(shownCount).join('')

	return (
		<span
			style={{
				display: 'inline-block',
				opacity: byWord ? entrance : 1,
				backgroundColor: boxed ? captionStyle.highlightColor : 'transparent',
				padding: boxed ? \`0 \${metrics.fontSize * 0.16}px\` : 0,
				borderRadius: metrics.fontSize * 0.16,
				transform: \`translate(\${effectX.toFixed(2)}px, \${(rise + effectY).toFixed(
					2,
				)}px) scale(\${scale.toFixed(3)}) rotateX(\${effectRotate.toFixed(1)}deg)\`,
				WebkitTextStroke:
					metrics.strokeWidth > 0
						? \`\${metrics.strokeWidth.toFixed(2)}px \${captionStyle.strokeColor}\`
						: undefined,
				// Stroke under fill: the default paint order eats into the letterform
				// and thins out every glyph at social-video outline weights.
				paintOrder: 'stroke fill',
				textShadow: shadow || 'none',
				...fill,
			}}
		>
			{shown}
			{hidden ? <span style={{ opacity: 0 }}>{hidden}</span> : null}
		</span>
	)
}

/* ------------------------------------------------------------------- cue */

const CueLayer = ({ cue, captionStyle }: { cue: CaptionCue; captionStyle: CaptionStyle }) => {
	const frame = useCurrentFrame()
	const { fps, height } = useVideoConfig()

	// Inside a <Sequence> the frame is cue-relative, so the absolute media time
	// is the cue start plus however far we are into the cue.
	const timeMs = cue.startMs + (frame / fps) * 1000
	const cueFrames = Math.max(1, Math.round(((cue.endMs - cue.startMs) / 1000) * fps))

	const lines = useMemo(
		() => balanceLines(cue.tokens, captionStyle.maxLines),
		[cue.tokens, captionStyle.maxLines],
	)

	const entrance = spring({
		frame,
		fps,
		config: { damping: 200, mass: 0.5, stiffness: 180 },
		durationInFrames: Math.min(9, cueFrames),
	})
	const exitFrom = Math.max(1, cueFrames - 4)
	const exitTo = Math.max(exitFrom + 1, cueFrames)
	const exit = interpolate(frame, [exitFrom, exitTo], [1, 0], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	})

	// With a word reveal the words carry the entrance themselves; the block only
	// handles the exit, otherwise every word would fade in twice.
	const byWord = captionStyle.reveal === 'word'
	const typewriter = captionStyle.reveal === 'typewriter'
	const animated = captionStyle.animation !== 'none'
	// The fade starts at 0.35 rather than 0: a caption that is fully transparent
	// on its own first frame reads as a flicker, and as a missing caption when
	// the preview is parked on that frame.
	const fadeIn = interpolate(frame, [0, Math.min(3, cueFrames)], [0.35, 1], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	})
	const opacity = byWord ? exit : animated ? Math.min(fadeIn, exit) : 1
	const scale = !byWord && captionStyle.animation === 'pop' ? 0.82 + entrance * 0.18 : 1
	const translateY =
		!byWord && captionStyle.animation === 'slide'
			? (1 - entrance) * height * 0.045
			: !byWord && captionStyle.animation === 'rise'
				? (1 - entrance) * height * 0.02
				: 0
	const blurPx =
		!byWord && captionStyle.animation === 'blur' ? (1 - entrance) * height * 0.012 : 0

	const fontSize = (height * captionStyle.fontSizePercent) / 100
	const shadowColor = captionStyle.shadowColor || '#000000'

	// Faked depth: a stack of hard shadows one pixel apart reads as an extruded
	// edge, and unlike a blur it stays crisp when the video is scaled.
	const extrudeSteps = Math.round(captionStyle.extrude * fontSize * 0.055)
	const extrudeShadow =
		captionStyle.extrude > 0 && extrudeSteps > 0
			? Array.from({ length: extrudeSteps }, (_, step) => {
					const offset = (step + 1) * (fontSize * 0.012)
					return \`\${offset.toFixed(2)}px \${offset.toFixed(2)}px 0 \${captionStyle.extrudeColor}\`
				}).join(', ')
			: ''

	const glowShadow =
		captionStyle.glow > 0
			? \`0 0 \${(fontSize * 0.22 * captionStyle.glow).toFixed(1)}px \${withAlpha(
					captionStyle.glowColor,
					Math.min(1, captionStyle.glow * 0.85),
				)}\`
			: ''
	const activeGlowShadow =
		captionStyle.glow > 0
			? \`\${glowShadow}, 0 0 \${(fontSize * 0.45 * captionStyle.glow).toFixed(1)}px \${
					captionStyle.glowColor
				}\`
			: captionStyle.preset === 'neon'
				? \`0 0 \${(fontSize * 0.38).toFixed(1)}px \${captionStyle.highlightColor}\`
				: ''

	const metrics: WordMetrics = {
		fontSize,
		strokeWidth: (fontSize * captionStyle.strokeWidth) / 100,
		// Two shadows, not one: the tight contact shadow anchors the type to the
		// picture, the wide one lifts it off whatever is moving behind it.
		dropShadow:
			captionStyle.shadow > 0
				? \`0 \${(fontSize * 0.035).toFixed(1)}px \${(fontSize * 0.07).toFixed(1)}px \${withAlpha(
						shadowColor,
						Math.min(1, captionStyle.shadow * 1.1),
					)}, 0 \${(fontSize * 0.09).toFixed(1)}px \${(fontSize * 0.3).toFixed(1)}px \${withAlpha(
						shadowColor,
						captionStyle.shadow * 0.7,
					)}\`
				: '',
		extrudeShadow,
		glowShadow,
		activeGlowShadow,
	}

	/**
	 * Typewriter reveal. Each word types across its own timestamp rather than
	 * across the whole cue, so the text lands with the voice instead of drifting
	 * ahead of it on a fast line.
	 */
	const typedFor = (token: CaptionToken): number | null => {
		if (!typewriter) return null
		if (timeMs >= token.toMs) return 1
		if (timeMs < token.fromMs) return 0
		return clamp01((timeMs - token.fromMs) / Math.max(1, token.toMs - token.fromMs))
	}

	const align = alignFor(captionStyle.align)

	return (
		<AbsoluteFill
			style={{
				display: 'flex',
				flexDirection: 'column',
				alignItems: align,
				justifyContent: justifyFor(captionStyle.placement),
				paddingLeft: captionStyle.align === 'left' ? \`\${(100 - captionStyle.maxWidthPercent) / 2}%\` : 0,
				paddingRight: captionStyle.align === 'right' ? \`\${(100 - captionStyle.maxWidthPercent) / 2}%\` : 0,
				paddingTop:
					captionStyle.placement === 'top' ? (height * captionStyle.offsetPercent) / 100 : 0,
				paddingBottom:
					captionStyle.placement === 'bottom' ? (height * captionStyle.offsetPercent) / 100 : 0,
			}}
		>
			<div
				style={{
					display: 'flex',
					flexDirection: 'column',
					alignItems: align,
					rowGap: fontSize * (captionStyle.lineHeight - 1),
					maxWidth: \`\${captionStyle.maxWidthPercent}%\`,
					padding:
						captionStyle.background === 'none'
							? 0
							: \`\${fontSize * 0.26}px \${fontSize * 0.5}px\`,
					borderRadius: captionStyle.background === 'pill' ? fontSize * 1.2 : fontSize * 0.2,
					backgroundColor:
						captionStyle.background === 'none'
							? 'transparent'
							: withAlpha(captionStyle.backgroundColor, captionStyle.backgroundOpacity),
					backdropFilter:
						captionStyle.backdropBlur > 0 ? \`blur(\${captionStyle.backdropBlur}px)\` : undefined,
					WebkitBackdropFilter:
						captionStyle.backdropBlur > 0 ? \`blur(\${captionStyle.backdropBlur}px)\` : undefined,
					opacity,
					filter: blurPx > 0 ? \`blur(\${blurPx.toFixed(2)}px)\` : undefined,
					transform: \`translateY(\${translateY.toFixed(2)}px) scale(\${scale.toFixed(
						3,
					)}) rotate(\${captionStyle.tilt}deg)\`,
					fontFamily: FONT_STACK,
					fontWeight: FONT_STATIC_WEIGHT ?? captionStyle.fontWeight,
					fontSize,
					lineHeight: captionStyle.lineHeight,
					letterSpacing: captionStyle.letterSpacing,
					textTransform: caseFor(captionStyle.textCase),
					textAlign: captionStyle.align,
				}}
			>
				{lines.map((line, lineIndex) => (
					<div
						key={\`\${cue.id}-line-\${lineIndex}\`}
						style={{
							display: 'flex',
							flexWrap: 'wrap',
							alignItems: 'center',
							justifyContent: align,
							columnGap: fontSize * 0.24,
							rowGap: fontSize * 0.1,
						}}
					>
						{line.map((token, tokenIndex) => (
							<CaptionWord
								key={\`\${cue.id}-\${lineIndex}-\${tokenIndex}\`}
								token={token}
								cueStartMs={cue.startMs}
								timeMs={timeMs}
								lineEntrance={entrance}
								captionStyle={captionStyle}
								metrics={metrics}
								index={tokenIndex}
								typed={typedFor(token)}
							/>
						))}
					</div>
				))}
			</div>
		</AbsoluteFill>
	)
}

/* ------------------------------------------------------------- safe area */

/**
 * Preview-only framing guides: the dashed box is the title-safe area and the
 * tinted strip is roughly where a vertical feed puts its own buttons and
 * caption text. Renders never pass this prop, so no export carries the guides.
 */
const SafeAreaGuides = () => {
	const { width, height } = useVideoConfig()
	const inset = Math.round(Math.min(width, height) * 0.05)
	const line = Math.max(1, Math.round(width / 800))

	return (
		<AbsoluteFill>
			<div
				style={{
					position: 'absolute',
					left: inset,
					right: inset,
					top: inset,
					bottom: inset,
					border: \`\${line}px dashed rgba(255, 255, 255, 0.4)\`,
					borderRadius: inset / 2,
				}}
			/>
			<div
				style={{
					position: 'absolute',
					left: 0,
					right: 0,
					bottom: 0,
					height: Math.round(height * 0.13),
					background: 'rgba(233, 115, 102, 0.16)',
					borderTop: \`\${line}px dashed rgba(233, 115, 102, 0.5)\`,
				}}
			/>
		</AbsoluteFill>
	)
}

/* ----------------------------------------------------------- composition */

export const CaptionedVideo = ({
	src = VIDEO_SRC,
	captions = CAPTIONS,
	captionStyle = CAPTION_STYLE,
	showSafeArea = false,
}: {
	src?: string
	captions?: CaptionCue[]
	captionStyle?: CaptionStyle
	showSafeArea?: boolean
}) => {
	const { fps } = useVideoConfig()

	return (
		<AbsoluteFill style={{ backgroundColor: '#000000' }}>
			<Video src={src} objectFit="cover" style={{ width: '100%', height: '100%' }} />

			{captionStyle.scrim > 0 && captions.length > 0 ? (
				<CaptionScrim captions={captions} captionStyle={captionStyle} />
			) : null}

			{captions.map((cue) => {
				const from = Math.max(0, Math.round((cue.startMs / 1000) * fps))
				const durationInFrames = Math.max(1, Math.round((cue.endMs / 1000) * fps) - from)
				return (
					<Sequence
						key={cue.id}
						from={from}
						durationInFrames={durationInFrames}
						name={cue.text.slice(0, 24)}
						layout="none"
					>
						<CueLayer cue={cue} captionStyle={captionStyle} />
					</Sequence>
				)
			})}

			{showSafeArea ? <SafeAreaGuides /> : null}
		</AbsoluteFill>
	)
}

const Root = () => (
	<>
		<Composition
			id={TIMELINE.id}
			component={CaptionedVideo}
			width={TIMELINE.width}
			height={TIMELINE.height}
			fps={TIMELINE.fps}
			durationInFrames={TIMELINE.durationInFrames}
			defaultProps={{ src: VIDEO_SRC, captions: CAPTIONS, captionStyle: CAPTION_STYLE }}
		/>
	</>
)

registerRoot(Root)

export default CaptionedVideo
`
}
