/**
 * The caption typography kit.
 *
 * Every family here is bundled under public/assets/fonts/v1 by
 * `npm run assets:fonts`, so a caption looks identical in the preview, in a
 * browser export and on a render host - no font is fetched from the network
 * while frames are being drawn, and a missing family can never silently fall
 * back to Arial mid-render.
 *
 * The table is deliberately large. "Which font" is the loudest styling decision
 * in a subtitle, and a studio that offers six of them quietly decides how every
 * video looks. Faces are grouped by the job they do rather than by foundry:
 * text faces that stay readable at 40 lines of dialogue, condensed faces for
 * dense vertical frames, display and comic faces for hooks, retro and pixel
 * faces for gaming and glitch edits, script faces for lifestyle, and a full
 * shelf of Devanagari for Nepali and Hindi.
 *
 * `variable` matters at render time: a static face has exactly one weight, and
 * asking a browser for 700 on a 400-only file produces a synthesised fake bold
 * that smears at caption size. The studio pins the weight for those faces
 * instead of letting the slider lie.
 */

export type CaptionFontCategory =
	| 'sans'
	| 'grotesk'
	| 'rounded'
	| 'condensed'
	| 'display'
	| 'comic'
	| 'serif'
	| 'tech'
	| 'retro'
	| 'pixel'
	| 'mono'
	| 'handwriting'
	| 'script'
	| 'devanagari'

export type CaptionFontFace = {
	family: string
	/** path under public/assets/fonts/v1 */
	file: string
	/** the CSS weight or weight range the file actually carries */
	weight: string
	variable: boolean
	/** where the weight slider lands when this face is chosen */
	defaultWeight: number
	category: CaptionFontCategory
	/** true when the face itself draws Devanagari, not just Latin */
	devanagari: boolean
	fallback: string
	label: string
	mood: string
	useFor: string
}

export const CAPTION_FACES = {
	inter: {
		family: 'Inter',
		file: 'inter/Inter[opsz,wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Inter - neutral',
		mood: 'neutral, modern, screen-first',
		useFor: 'UI, explainers, product videos, body copy at any size',
	},
	archivo: {
		family: 'Archivo',
		file: 'archivo/Archivo[wdth,wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'grotesk',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Archivo - editorial',
		mood: 'editorial grotesk with a width axis',
		useFor: 'headlines that must fit an exact box; condensed captions',
	},
	montserrat: {
		family: 'Montserrat',
		file: 'montserrat/Montserrat[wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Montserrat - mainstream geometric',
		mood: 'geometric, confident, familiar',
		useFor: 'brand videos, titles, captions that must feel mainstream',
	},
	poppins: {
		family: 'Poppins',
		file: 'poppins/Poppins-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Poppins - round geometric',
		mood: 'geometric, round, high contrast at size',
		useFor: 'social captions, product hooks, youthful brands',
	},
	outfit: {
		family: 'Outfit',
		file: 'outfit/Outfit[wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Outfit - clean geometric',
		mood: 'clean geometric, very even colour',
		useFor: 'startup explainers, clean lower thirds',
	},
	sora: {
		family: 'Sora',
		file: 'sora/Sora[wght].ttf',
		weight: '100 800',
		variable: true,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Sora - squared technical',
		mood: 'technical humanist with squared bowls',
		useFor: 'AI and fintech explainers, data storytelling',
	},
	plusJakartaSans: {
		family: 'Plus Jakarta Sans',
		file: 'plus-jakarta-sans/PlusJakartaSans[wght].ttf',
		weight: '200 800',
		variable: true,
		defaultWeight: 700,
		category: 'sans',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Plus Jakarta Sans - friendly geometric',
		mood: 'friendly geometric, wide language coverage',
		useFor: 'app promos, onboarding, multilingual captions',
	},
	nunito: {
		family: 'Nunito',
		file: 'nunito/Nunito[wght].ttf',
		weight: '200 1000',
		variable: true,
		defaultWeight: 700,
		category: 'rounded',
		devanagari: false,
		fallback: '"Trebuchet MS", Arial, sans-serif',
		label: 'Nunito - friendly',
		mood: 'friendly, soft, approachable',
		useFor: 'education, kids, health, onboarding and community videos',
	},
	fredoka: {
		family: 'Fredoka',
		file: 'fredoka/Fredoka[wdth,wght].ttf',
		weight: '300 700',
		variable: true,
		defaultWeight: 700,
		category: 'rounded',
		devanagari: false,
		fallback: '"Trebuchet MS", Arial, sans-serif',
		label: 'Fredoka - chunky rounded',
		mood: 'chunky, rounded, cheerful',
		useFor: 'kids content, playful brands, reaction captions',
	},
	oswald: {
		family: 'Oswald',
		file: 'oswald/Oswald[wght].ttf',
		weight: '200 700',
		variable: true,
		defaultWeight: 700,
		category: 'condensed',
		devanagari: false,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Oswald - news',
		mood: 'news, sport, documentary',
		useFor: 'stat overlays, tickers, documentary captions',
	},
	bebasNeue: {
		family: 'Bebas Neue',
		file: 'bebas-neue/BebasNeue-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'condensed',
		devanagari: false,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Bebas Neue - condensed',
		mood: 'tall, condensed, cinematic',
		useFor: 'title cards, lower thirds, trailer-style typography',
	},
	barlowCondensed: {
		family: 'Barlow Condensed',
		file: 'barlow-condensed/BarlowCondensed-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'condensed',
		devanagari: false,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Barlow Condensed - narrow technical',
		mood: 'narrow grotesk, technical',
		useFor: 'dense subtitles, sports scoreboards, tight vertical frames',
	},
	staatliches: {
		family: 'Staatliches',
		file: 'staatliches/Staatliches-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'condensed',
		devanagari: false,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Staatliches - poster caps',
		mood: 'poster caps, slightly rough',
		useFor: 'event promos, gig posters, hype captions',
	},
	kanit: {
		family: 'Kanit',
		file: 'kanit/Kanit-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'condensed',
		devanagari: false,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Kanit - slanted sport',
		mood: 'loud sans with a slight slant',
		useFor: 'sports, gym, motivational edits',
	},
	khand: {
		family: 'Khand',
		file: 'khand/Khand-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'condensed',
		devanagari: true,
		fallback: '"Arial Narrow", Arial, sans-serif',
		label: 'Khand - condensed - Devanagari',
		mood: 'condensed display that also writes Devanagari',
		useFor: 'Nepali and Hindi sports or news captions',
	},
	anton: {
		family: 'Anton',
		file: 'anton/Anton-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Anton - loud social',
		mood: 'heavy, loud, poster-like',
		useFor: 'social hooks, big single-word statements, sports and hype',
	},
	archivoBlack: {
		family: 'Archivo Black',
		file: 'archivo-black/ArchivoBlack-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Archivo Black - solid black',
		mood: 'solid black grotesk',
		useFor: 'statement captions, brand stings, callouts',
	},
	alfaSlabOne: {
		family: 'Alfa Slab One',
		file: 'alfa-slab-one/AlfaSlabOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Alfa Slab One - fat slab',
		mood: 'fat slab serif, circus poster',
		useFor: 'retro hooks, sale videos, loud storytelling',
	},
	titanOne: {
		family: 'Titan One',
		file: 'titan-one/TitanOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Titan One - cartoon weight',
		mood: 'inflated cartoon weight',
		useFor: 'gaming, kids, meme captions',
	},
	lilitaOne: {
		family: 'Lilita One',
		file: 'lilita-one/LilitaOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Lilita One - punchy caps',
		mood: 'punchy rounded caps',
		useFor: 'mobile-first captions, quiz and list videos',
	},
	rowdies: {
		family: 'Rowdies',
		file: 'rowdies/Rowdies-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Rowdies - stencil energy',
		mood: 'stencil-ish, energetic',
		useFor: 'street, music and skate edits',
	},
	bangers: {
		family: 'Bangers',
		file: 'bangers/Bangers-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'comic',
		devanagari: false,
		fallback: '"Comic Sans MS", Impact, sans-serif',
		label: 'Bangers - comic shout',
		mood: 'comic book shout',
		useFor: 'reaction videos, meme subtitles, action beats',
	},
	luckiestGuy: {
		family: 'Luckiest Guy',
		file: 'luckiest-guy/LuckiestGuy-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'comic',
		devanagari: false,
		fallback: '"Comic Sans MS", Impact, sans-serif',
		label: 'Luckiest Guy - cartoon brush',
		mood: 'cartoon brush caps',
		useFor: 'kids, gaming, playful hooks',
	},
	chewy: {
		family: 'Chewy',
		file: 'chewy/Chewy-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'comic',
		devanagari: false,
		fallback: '"Comic Sans MS", Impact, sans-serif',
		label: 'Chewy - bubbly comic',
		mood: 'soft bubbly comic',
		useFor: 'family content, food, light-hearted captions',
	},
	bungee: {
		family: 'Bungee',
		file: 'bungee/Bungee-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Bungee - urban signage',
		mood: 'urban signage, built for stacking',
		useFor: 'street style, vertical captions, city footage',
	},
	bungeeShade: {
		family: 'Bungee Shade',
		file: 'bungee-shade/BungeeShade-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Bungee Shade - built-in 3D',
		mood: 'signage with a built-in 3D shadow',
		useFor: 'title cards and one-word hooks that need no effects',
	},
	rubikMonoOne: {
		family: 'Rubik Mono One',
		file: 'rubik-mono-one/RubikMonoOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Rubik Mono One - heavy mono slab',
		mood: 'monospaced slab, very heavy',
		useFor: 'techno, crypto, brutalist edits',
	},
	shrikhand: {
		family: 'Shrikhand',
		file: 'shrikhand/Shrikhand-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'display',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Shrikhand - juicy poster',
		mood: 'juicy display with an Indian poster feel',
		useFor: 'food, festival and music captions',
	},
	playfairDisplay: {
		family: 'Playfair Display',
		file: 'playfair-display/PlayfairDisplay[wght].ttf',
		weight: '400 900',
		variable: true,
		defaultWeight: 700,
		category: 'serif',
		devanagari: false,
		fallback: 'Georgia, "Times New Roman", serif',
		label: 'Playfair Display - luxury serif',
		mood: 'elegant, luxury, editorial',
		useFor: 'fashion, food, real estate, wedding, premium brand films',
	},
	abrilFatface: {
		family: 'Abril Fatface',
		file: 'abril-fatface/AbrilFatface-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'serif',
		devanagari: false,
		fallback: 'Georgia, "Times New Roman", serif',
		label: 'Abril Fatface - magazine display',
		mood: 'high-contrast magazine display',
		useFor: 'editorial hooks, beauty, luxury product',
	},
	dmSerifDisplay: {
		family: 'DM Serif Display',
		file: 'dm-serif-display/DMSerifDisplay-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'serif',
		devanagari: false,
		fallback: 'Georgia, "Times New Roman", serif',
		label: 'DM Serif Display - refined serif',
		mood: 'refined transitional display',
		useFor: 'documentary titles, interviews, premium captions',
	},
	cinzel: {
		family: 'Cinzel',
		file: 'cinzel/Cinzel[wght].ttf',
		weight: '400 900',
		variable: true,
		defaultWeight: 700,
		category: 'serif',
		devanagari: false,
		fallback: 'Georgia, "Times New Roman", serif',
		label: 'Cinzel - inscriptional caps',
		mood: 'roman inscriptional caps',
		useFor: 'trailers, history, epic and cinematic titles',
	},
	spaceGrotesk: {
		family: 'Space Grotesk',
		file: 'space-grotesk/SpaceGrotesk[wght].ttf',
		weight: '300 700',
		variable: true,
		defaultWeight: 700,
		category: 'tech',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Space Grotesk - technical',
		mood: 'technical, futuristic, slightly quirky',
		useFor: 'developer tools, AI and crypto explainers, launch videos',
	},
	syne: {
		family: 'Syne',
		file: 'syne/Syne[wght].ttf',
		weight: '400 800',
		variable: true,
		defaultWeight: 700,
		category: 'tech',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Syne - gallery grotesk',
		mood: 'art-gallery grotesk with odd widths',
		useFor: 'design, music and fashion edits',
	},
	unbounded: {
		family: 'Unbounded',
		file: 'unbounded/Unbounded[wght].ttf',
		weight: '200 900',
		variable: true,
		defaultWeight: 700,
		category: 'tech',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Unbounded - wide contemporary',
		mood: 'wide geometric, very contemporary',
		useFor: 'web3, product launches, bold statements',
	},
	orbitron: {
		family: 'Orbitron',
		file: 'orbitron/Orbitron[wght].ttf',
		weight: '400 900',
		variable: true,
		defaultWeight: 700,
		category: 'tech',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Orbitron - sci-fi square',
		mood: 'square sci-fi',
		useFor: 'gaming, motorsport, HUD-style captions',
	},
	audiowide: {
		family: 'Audiowide',
		file: 'audiowide/Audiowide-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'tech',
		devanagari: false,
		fallback: 'Arial, Helvetica, sans-serif',
		label: 'Audiowide - chrome sci-fi',
		mood: 'chrome-era sci-fi display',
		useFor: 'esports, synthwave, tech reveals',
	},
	monoton: {
		family: 'Monoton',
		file: 'monoton/Monoton-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'retro',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Monoton - neon tube',
		mood: 'neon tube lettering, inline stripes',
		useFor: 'neon signage looks, music and nightlife',
	},
	righteous: {
		family: 'Righteous',
		file: 'righteous/Righteous-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'retro',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Righteous - art deco',
		mood: 'art-deco geometric',
		useFor: 'retro titles, podcasts, lifestyle',
	},
	pressStart2p: {
		family: 'Press Start 2P',
		file: 'press-start-2p/PressStart2P-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'pixel',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'Press Start 2P - 8-bit arcade',
		mood: '8-bit arcade pixels',
		useFor: 'retro gaming, speedruns, chiptune edits',
	},
	silkscreen: {
		family: 'Silkscreen',
		file: 'silkscreen/Silkscreen-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'pixel',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'Silkscreen - crisp pixels',
		mood: 'tiny crisp pixel face',
		useFor: 'UI overlays, glitch aesthetics, HUD labels',
	},
	vt323: {
		family: 'VT323',
		file: 'vt323/VT323-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'mono',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'VT323 - CRT terminal',
		mood: 'CRT terminal',
		useFor: 'hacker aesthetics, terminal recordings, horror edits',
	},
	jetbrainsMono: {
		family: 'JetBrains Mono',
		file: 'jetbrains-mono/JetBrainsMono[wght].ttf',
		weight: '100 800',
		variable: true,
		defaultWeight: 700,
		category: 'mono',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'JetBrains Mono - code',
		mood: 'code, terminal, data',
		useFor: 'code walkthroughs, labels, timestamps, technical annotation',
	},
	courierPrime: {
		family: 'Courier Prime',
		file: 'courier-prime/CourierPrime-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'mono',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'Courier Prime - screenplay',
		mood: 'screenplay typewriter',
		useFor: 'film scripts, documentary quotes, typewriter reveals',
	},
	specialElite: {
		family: 'Special Elite',
		file: 'special-elite/SpecialElite-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'mono',
		devanagari: false,
		fallback: 'ui-monospace, Consolas, monospace',
		label: 'Special Elite - battered typewriter',
		mood: 'battered typewriter with ink noise',
		useFor: 'true crime, vintage, found-footage edits',
	},
	rubikGlitch: {
		family: 'Rubik Glitch',
		file: 'rubik-glitch/RubikGlitch-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'retro',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Rubik Glitch - glitched',
		mood: 'broken scanline distortion, baked in',
		useFor: 'glitch transitions, error states, horror',
	},
	rubikWetPaint: {
		family: 'Rubik Wet Paint',
		file: 'rubik-wet-paint/RubikWetPaint-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'retro',
		devanagari: false,
		fallback: 'Impact, Haettenschweiler, sans-serif',
		label: 'Rubik Wet Paint - dripping paint',
		mood: 'dripping paint display',
		useFor: 'street art, music drops, halloween',
	},
	caveat: {
		family: 'Caveat',
		file: 'caveat/Caveat[wght].ttf',
		weight: '400 700',
		variable: true,
		defaultWeight: 700,
		category: 'handwriting',
		devanagari: false,
		fallback: '"Comic Sans MS", cursive',
		label: 'Caveat - handwritten',
		mood: 'handwritten, personal, annotative',
		useFor: 'annotations, circled emphasis, personal notes and vlogs',
	},
	permanentMarker: {
		family: 'Permanent Marker',
		file: 'permanent-marker/PermanentMarker-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'handwriting',
		devanagari: false,
		fallback: '"Comic Sans MS", cursive',
		label: 'Permanent Marker - marker pen',
		mood: 'thick marker pen',
		useFor: 'callouts, meme captions, whiteboard energy',
	},
	pacifico: {
		family: 'Pacifico',
		file: 'pacifico/Pacifico-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'script',
		devanagari: false,
		fallback: '"Brush Script MT", cursive',
		label: 'Pacifico - surf script',
		mood: 'surf brush script',
		useFor: 'travel, food, summer and lifestyle edits',
	},
	lobster: {
		family: 'Lobster',
		file: 'lobster/Lobster-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'script',
		devanagari: false,
		fallback: '"Brush Script MT", cursive',
		label: 'Lobster - bold script',
		mood: 'bold connected script',
		useFor: 'restaurant, retro brand, warm storytelling',
	},
	sedgwickAve: {
		family: 'Sedgwick Ave',
		file: 'sedgwick-ave/SedgwickAve-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'handwriting',
		devanagari: false,
		fallback: '"Comic Sans MS", cursive',
		label: 'Sedgwick Ave - graffiti marker',
		mood: 'graffiti marker',
		useFor: 'hip hop, street culture, skate videos',
	},
	notoSansDevanagari: {
		family: 'Noto Sans Devanagari',
		file: 'noto-sans-devanagari/NotoSansDevanagari[wdth,wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Noto Sans Devanagari - Devanagari, complete',
		mood: 'neutral, complete, highly legible',
		useFor: 'Nepali and Hindi subtitles, body copy and lower thirds',
	},
	anekDevanagari: {
		family: 'Anek Devanagari',
		file: 'anek-devanagari/AnekDevanagari[wdth,wght].ttf',
		weight: '100 800',
		variable: true,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Anek Devanagari - Devanagari, display',
		mood: 'contemporary, condensed, display-ready',
		useFor: 'loud Nepali social captions, titles and hooks',
	},
	notoSerifDevanagari: {
		family: 'Noto Serif Devanagari',
		file: 'noto-serif-devanagari/NotoSerifDevanagari[wdth,wght].ttf',
		weight: '100 900',
		variable: true,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Noto Serif Devanagari - Devanagari serif',
		mood: 'serif Devanagari with true contrast',
		useFor: 'documentary, literary and news Nepali captions',
	},
	mukta: {
		family: 'Mukta',
		file: 'mukta/Mukta-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Mukta - Devanagari, even',
		mood: 'humanist Devanagari, very even',
		useFor: 'general Nepali and Hindi subtitles at any size',
	},
	hind: {
		family: 'Hind',
		file: 'hind/Hind-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Hind - Devanagari, compact',
		mood: 'compact Devanagari built for screens',
		useFor: 'dense Nepali captions, news tickers',
	},
	baloo2: {
		family: 'Baloo 2',
		file: 'baloo-2/Baloo2[wght].ttf',
		weight: '400 800',
		variable: true,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Baloo 2 - Devanagari, rounded',
		mood: 'rounded, warm, display-friendly',
		useFor: 'playful Nepali captions, kids and lifestyle',
	},
	rozhaOne: {
		family: 'Rozha One',
		file: 'rozha-one/RozhaOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Rozha One - Devanagari, high contrast',
		mood: 'high-contrast Devanagari display',
		useFor: 'Nepali film titles, festival and poster captions',
	},
	yatraOne: {
		family: 'Yatra One',
		file: 'yatra-one/YatraOne-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Yatra One - Devanagari, brush',
		mood: 'brush-cut Devanagari display',
		useFor: 'Nepali music, travel and street content',
	},
	kalam: {
		family: 'Kalam',
		file: 'kalam/Kalam-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Kalam - Devanagari, handwritten',
		mood: 'handwritten Devanagari and Latin',
		useFor: 'personal vlogs, notes, informal Nepali captions',
	},
	tiroDevanagariHindi: {
		family: 'Tiro Devanagari Hindi',
		file: 'tiro-devanagari-hindi/TiroDevanagariHindi-Regular.ttf',
		weight: '400',
		variable: false,
		defaultWeight: 400,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Tiro Devanagari Hindi - Devanagari, calligraphic',
		mood: 'classical calligraphic Devanagari',
		useFor: 'literature, poetry, historical documentary',
	},
	martelSans: {
		family: 'Martel Sans',
		file: 'martel-sans/MartelSans-Bold.ttf',
		weight: '700',
		variable: false,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Martel Sans - Devanagari, sturdy',
		mood: 'sturdy Devanagari sans',
		useFor: 'interviews and explainers in Nepali or Hindi',
	},
	teko: {
		family: 'Teko',
		file: 'teko/Teko[wght].ttf',
		weight: '300 700',
		variable: true,
		defaultWeight: 700,
		category: 'devanagari',
		devanagari: true,
		fallback: '"Mangal", "Kokila", sans-serif',
		label: 'Teko - Devanagari, condensed',
		mood: 'condensed Devanagari and Latin display',
		useFor: 'Nepali sports, hype and scoreboard captions',
	},
} as const satisfies Record<string, CaptionFontFace>

export type CaptionFontId = keyof typeof CAPTION_FACES

/** The subset that can draw Devanagari - the companion face for Nepali. */
export type CaptionDevanagariFontId = {
	[Id in CaptionFontId]: (typeof CAPTION_FACES)[Id]['devanagari'] extends true ? Id : never
}[CaptionFontId]

export const CAPTION_FONTS: Record<CaptionFontId, CaptionFontFace> = CAPTION_FACES

export const CAPTION_FONT_IDS = Object.keys(CAPTION_FACES) as CaptionFontId[]

export const DEVANAGARI_FONT_IDS = CAPTION_FONT_IDS.filter(
	(id): id is CaptionDevanagariFontId => CAPTION_FACES[id].devanagari,
)

export const DEVANAGARI_FONTS = Object.fromEntries(
	DEVANAGARI_FONT_IDS.map((id) => [id, CAPTION_FACES[id]]),
) as Record<CaptionDevanagariFontId, CaptionFontFace>

export function isCaptionFontId(value: unknown): value is CaptionFontId {
	return typeof value === 'string' && value in CAPTION_FACES
}

export function fontById(id: string): CaptionFontFace {
	return isCaptionFontId(id) ? CAPTION_FACES[id] : CAPTION_FACES.inter
}

/**
 * A static face has one weight; letting the user ask for another only produces
 * a synthesised bold or a thin that the render host draws differently from the
 * preview. Variable faces are clamped to the range the file declares.
 */
export function resolveFontWeight(id: CaptionFontId, requested: number): number {
	const face = CAPTION_FACES[id]
	const range = face.weight.split(' ').map(Number)
	if (range.length === 1) return range[0]
	const [min, max] = range
	return Math.min(max, Math.max(min, Math.round(requested / 100) * 100))
}

export const CAPTION_FONT_CATEGORIES: { id: CaptionFontCategory | 'all'; label: string }[] = [
	{ id: 'all', label: 'All' },
	{ id: 'display', label: 'Display' },
	{ id: 'sans', label: 'Sans' },
	{ id: 'grotesk', label: 'Grotesk' },
	{ id: 'condensed', label: 'Condensed' },
	{ id: 'rounded', label: 'Rounded' },
	{ id: 'serif', label: 'Serif' },
	{ id: 'comic', label: 'Comic' },
	{ id: 'tech', label: 'Tech' },
	{ id: 'retro', label: 'Retro' },
	{ id: 'pixel', label: 'Pixel' },
	{ id: 'mono', label: 'Mono' },
	{ id: 'script', label: 'Script' },
	{ id: 'handwriting', label: 'Handwritten' },
	{ id: 'devanagari', label: 'Devanagari' },
]

/** Sample text that shows what a face is for, in the script it supports. */
export function previewTextFor(face: CaptionFontFace): string {
	return face.devanagari ? 'नमस्ते Nepali' : 'Aa Bb 123'
}
