import {
	CAPTION_FONT_IDS,
	CAPTION_FONTS,
	DEVANAGARI_FONT_IDS,
	DEVANAGARI_FONTS,
	fontById,
	resolveFontWeight,
} from './fonts'
import type {
	CaptionLayoutOptions,
	CaptionStyle,
	CaptionStylePresetId,
} from './types'

/**
 * The font tables moved to ./fonts, which owns the bundled kit and derives the
 * id unions from it. They are re-exported here because every caption module
 * already reaches for typography through this file.
 */
export {
	CAPTION_FONTS,
	CAPTION_FONT_IDS,
	DEVANAGARI_FONTS,
	DEVANAGARI_FONT_IDS,
	fontById,
	resolveFontWeight,
}

export const DEFAULT_LAYOUT: CaptionLayoutOptions = {
	maxWordsPerCue: 4,
	maxCharactersPerCue: 32,
	maxCueDurationMs: 2400,
	splitOnGapMs: 420,
	minCueMs: 700,
}

/**
 * Every preset starts from these values and overrides only what makes it
 * itself, so a field added to CaptionStyle can never leave a preset undefined.
 */
const BASE: CaptionStyle = {
	preset: 'tiktok',
	fontId: 'anton',
	fontWeight: 700,
	fontSizePercent: 5.4,
	textCase: 'upper',
	letterSpacing: 0,
	lineHeight: 1.16,
	textColor: '#ffffff',
	highlight: 'color',
	highlightColor: '#ffe14d',
	highlightTextColor: '#0b0b0b',
	strokeWidth: 10,
	strokeColor: '#000000',
	shadow: 0.55,
	background: 'none',
	backgroundColor: '#000000',
	backgroundOpacity: 0.55,
	placement: 'bottom',
	offsetPercent: 16,
	maxWidthPercent: 82,
	animation: 'pop',
	reveal: 'word',
	maxLines: 2,
	scrim: 0.18,
	devanagari: false,
	devanagariFontId: 'notoSansDevanagari',
	align: 'center',
	fill: 'solid',
	gradientFrom: '#ffd76f',
	gradientTo: '#ff7a45',
	gradientAngle: 90,
	karaokeFill: false,
	glow: 0,
	glowColor: '#4ad4ff',
	extrude: 0,
	extrudeColor: '#000000',
	shadowColor: '#000000',
	tilt: 0,
	backdropBlur: 0,
	wordEffect: 'none',
	emphasisWords: [],
	emphasisColor: '#ffe14d',
}

export type CaptionPresetDefinition = {
	id: CaptionStylePresetId
	name: string
	tagline: string
	/** colour the preset card is tinted with, so the grid reads at a glance */
	accent: string
	/** what this look is for - shown under the name in the picker */
	bestFor: string
	style: CaptionStyle
	layout: CaptionLayoutOptions
}

/**
 * Eighteen finished looks. Every field stays editable afterwards - a preset
 * only decides where the controls start, and picking one never touches cues
 * that were split or rewritten by hand.
 */
export const CAPTION_PRESETS: CaptionPresetDefinition[] = [
	{
		id: 'tiktok',
		name: 'Social pop',
		tagline: 'Big Anton caps, word pops in, thick outline.',
		accent: '#ffe14d',
		bestFor: '9:16 feeds, hooks, talking head',
		style: {
			...BASE,
			preset: 'tiktok',
			fontId: 'anton',
			fontSizePercent: 5.6,
			highlight: 'scale',
			strokeWidth: 11,
			shadow: 0.6,
			animation: 'pop',
			offsetPercent: 17,
			scrim: 0.16,
		},
		layout: {
			maxWordsPerCue: 3,
			maxCharactersPerCue: 24,
			maxCueDurationMs: 1800,
			splitOnGapMs: 380,
			minCueMs: 620,
		},
	},
	{
		id: 'money',
		name: 'Money caps',
		tagline: 'Archivo Black in a gold gradient with a heavy outline and a punch on every word.',
		accent: '#ffc531',
		bestFor: 'business, coaching, high-retention edits',
		style: {
			...BASE,
			preset: 'money',
			fontId: 'archivoBlack',
			fontWeight: 400,
			fontSizePercent: 6,
			fill: 'gradient',
			gradientFrom: '#fff3b0',
			gradientTo: '#f5a524',
			gradientAngle: 100,
			highlight: 'scale',
			highlightColor: '#ffffff',
			strokeWidth: 13,
			shadow: 0.7,
			wordEffect: 'pulse',
			offsetPercent: 18,
			scrim: 0.2,
			maxLines: 2,
		},
		layout: {
			maxWordsPerCue: 3,
			maxCharactersPerCue: 22,
			maxCueDurationMs: 1700,
			splitOnGapMs: 360,
			minCueMs: 600,
		},
	},
	{
		id: 'karaoke',
		name: 'Karaoke fill',
		tagline: 'The whole line stays up and the spoken word fills left to right.',
		accent: '#4ad4ff',
		bestFor: 'music, lyrics, language learning',
		style: {
			...BASE,
			preset: 'karaoke',
			fontId: 'bebasNeue',
			fontWeight: 400,
			fontSizePercent: 5.2,
			letterSpacing: 1,
			highlight: 'color',
			highlightColor: '#4ad4ff',
			karaokeFill: true,
			strokeWidth: 8,
			shadow: 0.45,
			animation: 'fade',
			offsetPercent: 14,
			reveal: 'line',
			scrim: 0.22,
		},
		layout: {
			maxWordsPerCue: 6,
			maxCharactersPerCue: 38,
			maxCueDurationMs: 2800,
			splitOnGapMs: 500,
			minCueMs: 780,
		},
	},
	{
		id: 'broadcast',
		name: 'Broadcast bar',
		tagline: 'Readable Inter on a translucent bar.',
		accent: '#e6e8f0',
		bestFor: 'documentary, interview, advertising',
		style: {
			...BASE,
			preset: 'broadcast',
			fontId: 'inter',
			fontWeight: 600,
			fontSizePercent: 3.9,
			textCase: 'none',
			lineHeight: 1.32,
			highlight: 'none',
			highlightColor: '#ffffff',
			strokeWidth: 0,
			shadow: 0.3,
			background: 'block',
			backgroundOpacity: 0.62,
			animation: 'fade',
			offsetPercent: 9,
			maxWidthPercent: 76,
			reveal: 'line',
			scrim: 0,
		},
		layout: {
			maxWordsPerCue: 9,
			maxCharactersPerCue: 46,
			maxCueDurationMs: 3600,
			splitOnGapMs: 600,
			minCueMs: 900,
		},
	},
	{
		id: 'glass',
		name: 'Frosted glass',
		tagline: 'Plus Jakarta Sans on a blurred pill - modern, quiet, product-safe.',
		accent: '#9fd6ff',
		bestFor: 'SaaS demos, app promos, UI walkthroughs',
		style: {
			...BASE,
			preset: 'glass',
			fontId: 'plusJakartaSans',
			fontWeight: 700,
			fontSizePercent: 3.8,
			textCase: 'none',
			lineHeight: 1.3,
			highlight: 'color',
			highlightColor: '#7cc4ff',
			strokeWidth: 0,
			shadow: 0.25,
			background: 'pill',
			backgroundColor: '#0b1220',
			backgroundOpacity: 0.35,
			backdropBlur: 18,
			animation: 'rise',
			offsetPercent: 10,
			maxWidthPercent: 72,
			reveal: 'line',
			scrim: 0,
		},
		layout: {
			maxWordsPerCue: 8,
			maxCharactersPerCue: 44,
			maxCueDurationMs: 3200,
			splitOnGapMs: 560,
			minCueMs: 860,
		},
	},
	{
		id: 'minimal',
		name: 'Clean minimal',
		tagline: 'No box, no outline, soft shadow only.',
		accent: '#c9cede',
		bestFor: 'product, lifestyle, fashion',
		style: {
			...BASE,
			preset: 'minimal',
			fontId: 'archivo',
			fontWeight: 600,
			fontSizePercent: 4.1,
			textCase: 'none',
			lineHeight: 1.28,
			highlight: 'color',
			highlightColor: '#ffffff',
			textColor: 'rgba(255,255,255,0.74)',
			strokeWidth: 0,
			shadow: 0.5,
			animation: 'slide',
			offsetPercent: 11,
			maxWidthPercent: 74,
			reveal: 'line',
			scrim: 0.26,
		},
		layout: {
			maxWordsPerCue: 6,
			maxCharactersPerCue: 40,
			maxCueDurationMs: 3000,
			splitOnGapMs: 520,
			minCueMs: 820,
		},
	},
	{
		id: 'cinema',
		name: 'Cinema serif',
		tagline: 'DM Serif Display, centred low, nothing moving. Lets the picture talk.',
		accent: '#efe3c8',
		bestFor: 'film, travel, brand storytelling',
		style: {
			...BASE,
			preset: 'cinema',
			fontId: 'dmSerifDisplay',
			fontWeight: 400,
			fontSizePercent: 4.2,
			textCase: 'none',
			letterSpacing: 0.4,
			lineHeight: 1.34,
			textColor: '#f7f1e3',
			highlight: 'none',
			strokeWidth: 0,
			shadow: 0.6,
			animation: 'fade',
			offsetPercent: 12,
			maxWidthPercent: 70,
			reveal: 'line',
			scrim: 0.3,
		},
		layout: {
			maxWordsPerCue: 8,
			maxCharactersPerCue: 44,
			maxCueDurationMs: 3400,
			splitOnGapMs: 620,
			minCueMs: 950,
		},
	},
	{
		id: 'neon',
		name: 'Neon glow',
		tagline: 'Space Grotesk with a coloured halo on the spoken word.',
		accent: '#ff5cf0',
		bestFor: 'music, gaming, tech',
		style: {
			...BASE,
			preset: 'neon',
			fontId: 'spaceGrotesk',
			fontWeight: 700,
			fontSizePercent: 4.8,
			letterSpacing: 2,
			highlight: 'color',
			highlightColor: '#ff5cf0',
			glow: 0.8,
			glowColor: '#ff5cf0',
			strokeWidth: 4,
			strokeColor: '#2a0044',
			shadow: 1,
			animation: 'pop',
			offsetPercent: 15,
			scrim: 0.3,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 28,
			maxCueDurationMs: 2000,
			splitOnGapMs: 420,
			minCueMs: 700,
		},
	},
	{
		id: 'tube',
		name: 'Neon tube',
		tagline: 'Monoton lettering that glows like bent glass, with the line held whole.',
		accent: '#42f5d4',
		bestFor: 'nightlife, synthwave, bar and club promos',
		style: {
			...BASE,
			preset: 'tube',
			fontId: 'monoton',
			fontWeight: 400,
			fontSizePercent: 4.6,
			letterSpacing: 2,
			textColor: '#dffff8',
			highlight: 'color',
			highlightColor: '#42f5d4',
			glow: 1,
			glowColor: '#19c8ff',
			strokeWidth: 0,
			shadow: 0.4,
			shadowColor: '#04121c',
			animation: 'fade',
			reveal: 'line',
			offsetPercent: 15,
			maxLines: 2,
			scrim: 0.34,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 26,
			maxCueDurationMs: 2400,
			splitOnGapMs: 460,
			minCueMs: 760,
		},
	},
	{
		id: 'sunset',
		name: 'Sunset gradient',
		tagline: 'Poppins filled with a warm gradient, each word rising into place.',
		accent: '#ff7a45',
		bestFor: 'travel, wellness, lifestyle vlogs',
		style: {
			...BASE,
			preset: 'sunset',
			fontId: 'poppins',
			fontWeight: 700,
			fontSizePercent: 5,
			textCase: 'none',
			fill: 'gradient',
			gradientFrom: '#ffd66b',
			gradientTo: '#ff5f8f',
			gradientAngle: 120,
			highlight: 'scale',
			highlightColor: '#ffffff',
			strokeWidth: 6,
			strokeColor: '#2b0f24',
			shadow: 0.5,
			animation: 'rise',
			offsetPercent: 16,
			scrim: 0.2,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 28,
			maxCueDurationMs: 2100,
			splitOnGapMs: 440,
			minCueMs: 700,
		},
	},
	{
		id: 'chrome',
		name: 'Chrome Y2K',
		tagline: 'Audiowide with a silver gradient, a hard 3D edge and a slight tilt.',
		accent: '#b9c6d8',
		bestFor: 'esports, hype reels, product drops',
		style: {
			...BASE,
			preset: 'chrome',
			fontId: 'audiowide',
			fontWeight: 400,
			fontSizePercent: 4.8,
			letterSpacing: 1,
			fill: 'gradient',
			gradientFrom: '#ffffff',
			gradientTo: '#7f8ea3',
			gradientAngle: 160,
			highlight: 'color',
			highlightColor: '#8ad8ff',
			extrude: 0.7,
			extrudeColor: '#1b2534',
			strokeWidth: 5,
			strokeColor: '#0d131c',
			shadow: 0.35,
			tilt: -2.5,
			animation: 'pop',
			wordEffect: 'flip',
			offsetPercent: 16,
			scrim: 0.18,
		},
		layout: {
			maxWordsPerCue: 3,
			maxCharactersPerCue: 24,
			maxCueDurationMs: 1900,
			splitOnGapMs: 400,
			minCueMs: 640,
		},
	},
	{
		id: 'boxed',
		name: 'Accent box',
		tagline: 'Each spoken word gets a solid accent block behind it.',
		accent: '#ff4d4d',
		bestFor: 'news explainers, listicles, hooks',
		style: {
			...BASE,
			preset: 'boxed',
			fontId: 'oswald',
			fontWeight: 600,
			fontSizePercent: 4.9,
			highlight: 'box',
			highlightColor: '#ff4d4d',
			highlightTextColor: '#ffffff',
			strokeWidth: 0,
			shadow: 0.4,
			animation: 'slide',
			offsetPercent: 15,
			scrim: 0.12,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 30,
			maxCueDurationMs: 2200,
			splitOnGapMs: 440,
			minCueMs: 700,
		},
	},
	{
		id: 'comic',
		name: 'Comic slam',
		tagline: 'Bangers with a fat outline and a word that will not sit still.',
		accent: '#ffd23f',
		bestFor: 'reactions, memes, gaming clips',
		style: {
			...BASE,
			preset: 'comic',
			fontId: 'bangers',
			fontWeight: 400,
			fontSizePercent: 6.2,
			letterSpacing: 1,
			textColor: '#fff8e7',
			highlight: 'color',
			highlightColor: '#ffd23f',
			strokeWidth: 12,
			strokeColor: '#12060b',
			shadow: 0.55,
			extrude: 0.35,
			extrudeColor: '#c1121f',
			tilt: -3,
			wordEffect: 'jitter',
			animation: 'pop',
			offsetPercent: 18,
			scrim: 0.14,
		},
		layout: {
			maxWordsPerCue: 3,
			maxCharactersPerCue: 22,
			maxCueDurationMs: 1700,
			splitOnGapMs: 360,
			minCueMs: 600,
		},
	},
	{
		id: 'arcade',
		name: 'Arcade',
		tagline: 'Press Start 2P pixels on a hard black block, one word at a time.',
		accent: '#5cff8f',
		bestFor: 'retro gaming, speedruns, chiptune',
		style: {
			...BASE,
			preset: 'arcade',
			fontId: 'pressStart2p',
			fontWeight: 400,
			fontSizePercent: 2.8,
			letterSpacing: 0,
			lineHeight: 1.6,
			textColor: '#eaffef',
			highlight: 'box',
			highlightColor: '#5cff8f',
			highlightTextColor: '#04140a',
			strokeWidth: 0,
			shadow: 0.4,
			shadowColor: '#0b2a16',
			background: 'block',
			backgroundColor: '#04140a',
			backgroundOpacity: 0.78,
			animation: 'none',
			reveal: 'word',
			offsetPercent: 13,
			maxWidthPercent: 78,
			scrim: 0,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 26,
			maxCueDurationMs: 2200,
			splitOnGapMs: 460,
			minCueMs: 760,
		},
	},
	{
		id: 'vhs',
		name: 'VHS tape',
		tagline: 'VT323 terminal type with a magenta ghost and a restless jitter.',
		accent: '#ff5edb',
		bestFor: 'found footage, horror, retro edits',
		style: {
			...BASE,
			preset: 'vhs',
			fontId: 'vt323',
			fontWeight: 400,
			fontSizePercent: 5,
			textCase: 'upper',
			letterSpacing: 1,
			textColor: '#e9fbff',
			highlight: 'color',
			highlightColor: '#ff5edb',
			extrude: 0.5,
			extrudeColor: '#22c1ff',
			strokeWidth: 0,
			shadow: 0.3,
			shadowColor: '#12001a',
			wordEffect: 'jitter',
			animation: 'blur',
			reveal: 'line',
			offsetPercent: 12,
			scrim: 0.24,
		},
		layout: {
			maxWordsPerCue: 6,
			maxCharactersPerCue: 36,
			maxCueDurationMs: 2600,
			splitOnGapMs: 520,
			minCueMs: 780,
		},
	},
	{
		id: 'typewriter',
		name: 'Typewriter',
		tagline: 'Courier Prime typed out character by character, on a paper-dark bar.',
		accent: '#d9c9a3',
		bestFor: 'true crime, essays, quote cards',
		style: {
			...BASE,
			preset: 'typewriter',
			fontId: 'courierPrime',
			fontWeight: 400,
			fontSizePercent: 3.6,
			textCase: 'none',
			letterSpacing: 0.5,
			lineHeight: 1.4,
			textColor: '#f4ead6',
			highlight: 'none',
			strokeWidth: 0,
			shadow: 0.25,
			background: 'block',
			backgroundColor: '#100d09',
			backgroundOpacity: 0.72,
			animation: 'none',
			reveal: 'typewriter',
			align: 'left',
			offsetPercent: 10,
			maxWidthPercent: 68,
			scrim: 0,
		},
		layout: {
			maxWordsPerCue: 10,
			maxCharactersPerCue: 48,
			maxCueDurationMs: 3800,
			splitOnGapMs: 620,
			minCueMs: 1000,
		},
	},
	{
		id: 'marker',
		name: 'Marker note',
		tagline: 'Permanent Marker at an angle, bouncing on the word being said.',
		accent: '#ff8f5c',
		bestFor: 'vlogs, tutorials, personal stories',
		style: {
			...BASE,
			preset: 'marker',
			fontId: 'permanentMarker',
			fontWeight: 400,
			fontSizePercent: 5.2,
			textCase: 'none',
			textColor: '#fffdf7',
			highlight: 'color',
			highlightColor: '#ff8f5c',
			strokeWidth: 7,
			strokeColor: '#1a1207',
			shadow: 0.5,
			tilt: -3.5,
			wordEffect: 'bounce',
			animation: 'pop',
			offsetPercent: 15,
			scrim: 0.18,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 28,
			maxCueDurationMs: 2100,
			splitOnGapMs: 440,
			minCueMs: 700,
		},
	},
	{
		id: 'nepali',
		name: 'Nepali bold',
		tagline: 'Khand for Devanagari and Latin together, with Anek as the companion face.',
		accent: '#ff6b6b',
		bestFor: 'Nepali and Hindi social video',
		style: {
			...BASE,
			preset: 'nepali',
			fontId: 'khand',
			fontWeight: 700,
			fontSizePercent: 5.4,
			textCase: 'none',
			lineHeight: 1.3,
			highlight: 'scale',
			highlightColor: '#ffd166',
			strokeWidth: 9,
			shadow: 0.55,
			animation: 'pop',
			offsetPercent: 16,
			devanagari: true,
			devanagariFontId: 'anekDevanagari',
			scrim: 0.2,
		},
		layout: {
			maxWordsPerCue: 4,
			maxCharactersPerCue: 26,
			maxCueDurationMs: 2200,
			splitOnGapMs: 420,
			minCueMs: 720,
		},
	},
]

export const DEFAULT_CAPTION_STYLE: CaptionStyle = CAPTION_PRESETS[0].style

export function presetById(id: CaptionStylePresetId): CaptionPresetDefinition {
	return CAPTION_PRESETS.find((preset) => preset.id === id) ?? CAPTION_PRESETS[0]
}
