/**
 * The house-style catalogue.
 *
 * A *template* is a complete art direction: the only backgrounds, layouts,
 * typography, accents, finishes, cameras, rhythm, palettes and font categories
 * a video built from it may use. Because every pool below is disjoint enough
 * from its neighbours, two videos built from different templates cannot read as
 * variants of one another.
 *
 * This file owns the recipe vocabularies as well as the catalogue so that the
 * two can never drift apart: adding an id here is the only place a new visual
 * idea enters the system, and `lib/ai/compose.ts` is the only place it is
 * drawn.
 */

import type { PaletteId } from './kit'

/* -------------------------------------------------------------------------- */
/*  Recipe vocabularies                                                       */
/* -------------------------------------------------------------------------- */

/** How the field behind every scene is painted. */
export const BACKGROUND_RECIPE_IDS = [
	'aurora',
	'spotlight',
	'paper-wash',
	'soft-orbits',
	'cinematic-bands',
	'ink-bloom',
	'duotone-split',
	'halo-sweep',
	'noir-fade',
	'gradient-mesh',
	'vertical-fade',
	'corner-glow',
	'editorial-slab',
	'flat-field',
	/* Added for the extended catalogue. */
	'drafting-wash',
	'halftone-drift',
	'topographic',
	'crt-glow',
	'liquid-chrome',
	'risograph',
	'sunburst-rays',
	'hex-scatter',
	'stripe-march',
	'terrazzo',
	'holo-foil',
	'vhs-tracking',
	'paper-fold',
	'iso-shards',
	'nebula-drift',
	'sand-dunes',
	'trace-lines',
	'kaleidoscope',
	'confetti-field',
	'aurora-veil',
	'concrete-slab',
	'ripple-rings',
] as const
export type BackgroundRecipeId = (typeof BACKGROUND_RECIPE_IDS)[number]

/** Where content sits inside the frame. */
export const LAYOUT_RECIPE_IDS = [
	'centered',
	'editorial-left',
	'offset-stack',
	'wide-stage',
	'poster',
	'split-vertical',
	'corner-anchor',
	'banner-top',
	'column-right',
	'full-bleed',
	/* Added for the extended catalogue. */
	'diagonal-split',
	'magazine-grid',
	'lower-third',
	'pillar-center',
	'margin-note',
	'cover-stack',
	'ticker-frame',
	'gutter-right',
	'baseline-drop',
	'quadrant',
] as const
export type LayoutRecipeId = (typeof LAYOUT_RECIPE_IDS)[number]

/** The cut language between scenes. */
export const TRANSITION_RECIPE_IDS = [
	'dissolve',
	'directional',
	'graphic-wipe',
	'mixed',
	'kinetic',
	/* Added for the extended catalogue. */
	'clock',
	'iris',
	'card-flip',
	'punch-cut',
	'hard-cut',
] as const
export type TransitionRecipeId = (typeof TRANSITION_RECIPE_IDS)[number]

export const SFX_RECIPE_IDS = ['cinematic', 'crisp', 'organic', 'digital', 'minimal'] as const
export type SfxRecipeId = (typeof SFX_RECIPE_IDS)[number]

/** How type is set: weight, tracking, casing appetite and italic tolerance. */
export const TYPOGRAPHY_RECIPE_IDS = [
	'poster',
	'editorial',
	'technical',
	'friendly',
	'cinematic',
	'brutalist',
	'condensed-stack',
	'serif-luxe',
	'mono-terminal',
	'handwritten',
	/* Added for the extended catalogue. */
	'display-swash',
	'pixel-arcade',
	'stencil-industrial',
	'geometric-round',
	'ransom-cut',
	'grotesk-tight',
	'wide-track',
	'comic-punch',
] as const
export type TypographyRecipeId = (typeof TYPOGRAPHY_RECIPE_IDS)[number]

/** How the virtual camera behaves over a scene. */
export const CAMERA_RECIPE_IDS = [
	'still',
	'drift',
	'dolly',
	'orbit',
	/* Added for the extended catalogue. */
	'push-in',
	'pull-out',
	'handheld',
	'sway',
	'crane',
] as const
export type CameraRecipeId = (typeof CAMERA_RECIPE_IDS)[number]

/** The finishing pass laid over the whole frame. */
export const FINISH_RECIPE_IDS = [
	'clean',
	'film',
	'paper',
	'luminous',
	'matte',
	'print',
	/* Added for the extended catalogue. */
	'chrome',
	'riso',
	'glass',
	'neon',
	'noir',
	'bloom',
	'xerox',
] as const
export type FinishRecipeId = (typeof FINISH_RECIPE_IDS)[number]

/** Large decorative geometry drawn behind the content. */
export const ACCENT_SHAPE_IDS = [
	'rings',
	'ribbons',
	'discs',
	'frames',
	'sparks',
	'arcs',
	'slashes',
	'blocks',
	'halo',
	'none',
	/* Added for the extended catalogue. */
	'measure-marks',
	'crosshair',
	'chevrons',
	'triangles',
	'waves',
	'pills',
	'starfield',
	'corner-ticks',
	'hex-cluster',
	'orbits',
	'bar-code',
] as const
export type AccentShapeId = (typeof ACCENT_SHAPE_IDS)[number]

/** How headline and label copy is cased. */
export const TEXT_CASE_IDS = ['title', 'upper', 'sentence'] as const
export type TextCaseId = (typeof TEXT_CASE_IDS)[number]

/** Corner language for every card, badge and plate. */
export const CORNER_STYLE_IDS = ['sharp', 'soft', 'pill'] as const
export type CornerStyleId = (typeof CORNER_STYLE_IDS)[number]

/** How a divider under a headline is drawn. */
export const RULE_STYLE_IDS = [
	'bar',
	'thin',
	'double',
	'dotted',
	'none',
	/* Added for the extended catalogue. */
	'dashed',
	'ticked',
	'gradient',
	'bracket',
	'zigzag',
] as const
export type RuleStyleId = (typeof RULE_STYLE_IDS)[number]

/** The signature treatment applied to the main headline of a scene. */
export const TITLE_TREATMENT_IDS = [
	'stack',
	'inline',
	'boxed',
	'underline',
	'outline',
	'sidebar',
	/* Added for the extended catalogue. */
	'plate',
	'ghost',
	'marquee',
	'tag',
	'cutout',
	'shadowbox',
	'bookend',
] as const
export type TitleTreatmentId = (typeof TITLE_TREATMENT_IDS)[number]

/**
 * The animation language a house style uses to bring elements on.
 *
 * This is the axis that stops two videos with the same palette and layout from
 * still feeling identical: `slam` lands hard on the beat, `unfold` rotates in
 * on a hinge, `typewriter` reveals character by character, and so on.
 */
export const MOTION_SIGNATURE_IDS = [
	'rise',
	'slam',
	'unfold',
	'typewriter',
	'sweep',
	'zoom-punch',
	'blur-in',
	'mask-reveal',
	'stagger-drop',
	'elastic',
	'glitch',
	'spin-in',
	'scale-fade',
	'slide-shutter',
] as const
export type MotionSignatureId = (typeof MOTION_SIGNATURE_IDS)[number]

/* -------------------------------------------------------------------------- */
/*  Template recipes                                                          */
/* -------------------------------------------------------------------------- */

export type TemplateRecipe = {
	/** Human label used in the Studio UI and generation summaries. */
	label: string
	backgrounds: readonly BackgroundRecipeId[]
	layouts: readonly LayoutRecipeId[]
	typography: readonly TypographyRecipeId[]
	accents: readonly AccentShapeId[]
	finishes: readonly FinishRecipeId[]
	cameras: readonly CameraRecipeId[]
	transitions: readonly TransitionRecipeId[]
	sfx: readonly SfxRecipeId[]
	textCase: readonly TextCaseId[]
	corners: readonly CornerStyleId[]
	rules: readonly RuleStyleId[]
	titles: readonly TitleTreatmentId[]
	motion: readonly MotionSignatureId[]
	tempo: readonly number[]
	/** Font categories the template draws headline and body faces from. */
	displayFontCategories: readonly string[]
	bodyFontCategories: readonly string[]
	/** Palettes that suit the house style, used when the brief names none. */
	palettes: readonly PaletteId[]
	/**
	 * Narrative arcs this house style tells well. The planner picks one of
	 * these when the brief does not force a structure, which is what makes two
	 * generations differ in *content shape*, not only in colour.
	 */
	arcs: readonly string[]
}

export const TEMPLATE_KIT = {
	/* ---- Editorial and print ------------------------------------------- */
	'editorial-press': {
		label: 'Editorial Press',
		backgrounds: ['paper-wash', 'editorial-slab', 'vertical-fade', 'flat-field'],
		layouts: ['editorial-left', 'column-right', 'offset-stack', 'margin-note'],
		typography: ['editorial', 'serif-luxe'],
		accents: ['frames', 'slashes', 'none', 'corner-ticks'],
		finishes: ['paper', 'print', 'matte'],
		cameras: ['still', 'drift'],
		transitions: ['dissolve', 'directional'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['sharp', 'soft'],
		rules: ['thin', 'double', 'bar'],
		titles: ['stack', 'underline', 'sidebar', 'bookend'],
		motion: ['rise', 'blur-in', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92, 0.96],
		displayFontCategories: ['serif', 'condensed'],
		bodyFontCategories: ['serif', 'sans', 'grotesk'],
		palettes: ['paper', 'heritage', 'mono', 'arctic'],
		arcs: ['feature-lede', 'three-act', 'thesis-proof', 'long-read'],
	},
	'swiss-poster': {
		label: 'Swiss Poster',
		backgrounds: ['flat-field', 'duotone-split', 'editorial-slab', 'corner-glow'],
		layouts: ['poster', 'corner-anchor', 'banner-top', 'quadrant'],
		typography: ['poster', 'brutalist', 'condensed-stack', 'grotesk-tight'],
		accents: ['blocks', 'slashes', 'none', 'measure-marks'],
		finishes: ['clean', 'matte', 'print'],
		cameras: ['still', 'push-in'],
		transitions: ['graphic-wipe', 'directional'],
		sfx: ['crisp', 'minimal'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['bar', 'double', 'none'],
		titles: ['stack', 'boxed', 'sidebar'],
		motion: ['slam', 'slide-shutter', 'mask-reveal'],
		tempo: [0.92, 0.96, 1, 1.04],
		displayFontCategories: ['condensed', 'grotesk', 'sans', 'display'],
		bodyFontCategories: ['grotesk', 'sans', 'condensed'],
		palettes: ['mono', 'arctic', 'azure', 'sunrise', 'paper'],
		arcs: ['manifesto', 'poster-series', 'thesis-proof', 'index-cards'],
	},
	'archive-paper': {
		label: 'Archive Paper',
		backgrounds: ['paper-wash', 'ink-bloom', 'vertical-fade', 'concrete-slab'],
		layouts: ['editorial-left', 'centered', 'offset-stack', 'margin-note'],
		typography: ['serif-luxe', 'editorial', 'handwritten'],
		accents: ['frames', 'none', 'corner-ticks', 'bar-code'],
		finishes: ['paper', 'print', 'xerox'],
		cameras: ['still', 'drift'],
		transitions: ['dissolve', 'graphic-wipe'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['sharp', 'soft'],
		rules: ['thin', 'dotted', 'dashed'],
		titles: ['stack', 'underline', 'bookend'],
		motion: ['blur-in', 'rise', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'handwriting', 'retro', 'condensed'],
		bodyFontCategories: ['serif', 'sans', 'handwriting'],
		palettes: ['paper', 'heritage', 'ember', 'mono'],
		arcs: ['archive-dig', 'chronicle', 'long-read', 'field-notes'],
	},
	'broadsheet-column': {
		label: 'Broadsheet Column',
		backgrounds: ['flat-field', 'editorial-slab', 'paper-wash', 'stripe-march'],
		layouts: ['magazine-grid', 'gutter-right', 'editorial-left'],
		typography: ['editorial', 'condensed-stack', 'serif-luxe'],
		accents: ['measure-marks', 'frames', 'none'],
		finishes: ['print', 'paper', 'clean'],
		cameras: ['still', 'drift'],
		transitions: ['directional', 'dissolve'],
		sfx: ['minimal', 'crisp'],
		textCase: ['title', 'sentence'],
		corners: ['sharp'],
		rules: ['double', 'thin', 'bracket'],
		titles: ['bookend', 'stack', 'sidebar'],
		motion: ['rise', 'stagger-drop', 'mask-reveal'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['serif', 'condensed', 'grotesk'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['paper', 'mono', 'arctic', 'slate'],
		arcs: ['feature-lede', 'long-read', 'index-cards', 'thesis-proof'],
	},
	'zine-collage': {
		label: 'Zine Collage',
		backgrounds: ['paper-wash', 'ink-bloom', 'duotone-split', 'risograph'],
		layouts: ['offset-stack', 'corner-anchor', 'split-vertical', 'quadrant'],
		typography: ['brutalist', 'handwritten', 'condensed-stack', 'ransom-cut'],
		accents: ['slashes', 'blocks', 'sparks', 'ribbons', 'triangles'],
		finishes: ['print', 'paper', 'riso', 'xerox'],
		cameras: ['still', 'handheld'],
		transitions: ['graphic-wipe', 'kinetic', 'mixed'],
		sfx: ['organic', 'crisp'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['dotted', 'bar', 'zigzag', 'none'],
		titles: ['boxed', 'outline', 'cutout', 'tag'],
		motion: ['slam', 'stagger-drop', 'glitch', 'elastic'],
		tempo: [1, 1.04, 1.08, 1.12],
		displayFontCategories: ['retro', 'comic', 'display', 'condensed'],
		bodyFontCategories: ['sans', 'mono', 'condensed'],
		palettes: ['paper', 'sunrise', 'mono', 'ember'],
		arcs: ['scrapbook', 'manifesto', 'rapid-list', 'hot-take'],
	},
	'riso-print': {
		label: 'Riso Print',
		backgrounds: ['risograph', 'duotone-split', 'flat-field', 'halftone-drift'],
		layouts: ['poster', 'offset-stack', 'centered', 'cover-stack'],
		typography: ['brutalist', 'poster', 'geometric-round'],
		accents: ['blocks', 'discs', 'triangles', 'waves'],
		finishes: ['riso', 'print', 'paper'],
		cameras: ['still', 'sway'],
		transitions: ['graphic-wipe', 'punch-cut'],
		sfx: ['organic', 'crisp'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['bar', 'dashed', 'none'],
		titles: ['cutout', 'boxed', 'stack'],
		motion: ['slam', 'slide-shutter', 'stagger-drop'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['display', 'retro', 'grotesk', 'condensed'],
		bodyFontCategories: ['sans', 'grotesk', 'mono'],
		palettes: ['sunrise', 'ember', 'paper', 'neon'],
		arcs: ['poster-series', 'rapid-list', 'manifesto', 'scrapbook'],
	},
	'xerox-punk': {
		label: 'Xerox Punk',
		backgrounds: ['concrete-slab', 'crt-glow', 'flat-field', 'stripe-march'],
		layouts: ['corner-anchor', 'offset-stack', 'full-bleed', 'quadrant'],
		typography: ['ransom-cut', 'brutalist', 'stencil-industrial'],
		accents: ['bar-code', 'slashes', 'blocks', 'corner-ticks'],
		finishes: ['xerox', 'noir', 'print'],
		cameras: ['handheld', 'still'],
		transitions: ['hard-cut', 'kinetic', 'punch-cut'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['zigzag', 'bar', 'ticked'],
		titles: ['cutout', 'outline', 'tag'],
		motion: ['glitch', 'slam', 'slide-shutter'],
		tempo: [1.08, 1.12, 1.16],
		displayFontCategories: ['condensed', 'display', 'retro', 'grotesk'],
		bodyFontCategories: ['mono', 'condensed', 'sans'],
		palettes: ['mono', 'ember', 'neon', 'slate'],
		arcs: ['manifesto', 'hot-take', 'rapid-list', 'myth-bust'],
	},

	/* ---- Motion and kinetic --------------------------------------------- */
	'kinetic-type': {
		label: 'Kinetic Type',
		backgrounds: ['flat-field', 'halo-sweep', 'spotlight', 'gradient-mesh'],
		layouts: ['centered', 'full-bleed', 'poster', 'baseline-drop'],
		typography: ['poster', 'brutalist', 'cinematic', 'grotesk-tight'],
		accents: ['sparks', 'arcs', 'halo', 'chevrons'],
		finishes: ['clean', 'luminous', 'bloom'],
		cameras: ['drift', 'dolly', 'push-in'],
		transitions: ['kinetic', 'directional', 'mixed', 'punch-cut'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper'],
		corners: ['sharp', 'pill'],
		rules: ['bar', 'gradient', 'none'],
		titles: ['stack', 'inline', 'outline', 'marquee'],
		motion: ['slam', 'zoom-punch', 'elastic', 'stagger-drop'],
		tempo: [1.04, 1.08, 1.12, 1.16],
		displayFontCategories: ['display', 'condensed', 'sans', 'grotesk'],
		bodyFontCategories: ['grotesk', 'sans', 'mono'],
		palettes: ['mono', 'neon', 'midnight', 'slate', 'sunrise'],
		arcs: ['hook-drop', 'rapid-list', 'manifesto', 'beat-drop'],
	},
	'lyric-slam': {
		label: 'Lyric Slam',
		backgrounds: ['flat-field', 'noir-fade', 'duotone-split', 'liquid-chrome'],
		layouts: ['centered', 'baseline-drop', 'full-bleed'],
		typography: ['display-swash', 'brutalist', 'poster'],
		accents: ['none', 'halo', 'starfield', 'waves'],
		finishes: ['bloom', 'luminous', 'chrome'],
		cameras: ['push-in', 'pull-out', 'sway'],
		transitions: ['punch-cut', 'kinetic', 'hard-cut'],
		sfx: ['crisp', 'cinematic'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['none', 'gradient'],
		titles: ['stack', 'marquee', 'ghost'],
		motion: ['zoom-punch', 'slam', 'elastic', 'scale-fade'],
		tempo: [1.08, 1.12, 1.16],
		displayFontCategories: ['display', 'condensed', 'grotesk'],
		bodyFontCategories: ['grotesk', 'sans'],
		palettes: ['midnight', 'neon', 'mono', 'royal'],
		arcs: ['beat-drop', 'hook-drop', 'manifesto', 'countdown'],
	},
	'typewriter-log': {
		label: 'Typewriter Log',
		backgrounds: ['paper-wash', 'flat-field', 'halftone-drift', 'concrete-slab'],
		layouts: ['editorial-left', 'margin-note', 'lower-third'],
		typography: ['mono-terminal', 'technical', 'editorial'],
		accents: ['measure-marks', 'none', 'corner-ticks'],
		finishes: ['paper', 'xerox', 'matte'],
		cameras: ['still'],
		transitions: ['hard-cut', 'dissolve'],
		sfx: ['minimal', 'crisp'],
		textCase: ['sentence', 'title'],
		corners: ['sharp'],
		rules: ['dashed', 'thin', 'ticked'],
		titles: ['stack', 'bookend', 'tag'],
		motion: ['typewriter', 'rise', 'blur-in'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['mono', 'condensed', 'serif'],
		bodyFontCategories: ['mono', 'sans'],
		palettes: ['paper', 'mono', 'heritage', 'slate'],
		arcs: ['field-notes', 'chronicle', 'archive-dig', 'long-read'],
	},
	'marquee-roll': {
		label: 'Marquee Roll',
		backgrounds: ['stripe-march', 'flat-field', 'sunburst-rays', 'confetti-field'],
		layouts: ['ticker-frame', 'banner-top', 'centered'],
		typography: ['poster', 'display-swash', 'wide-track'],
		accents: ['pills', 'chevrons', 'blocks'],
		finishes: ['clean', 'neon', 'bloom'],
		cameras: ['sway', 'drift'],
		transitions: ['directional', 'kinetic'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper'],
		corners: ['pill', 'sharp'],
		rules: ['bar', 'gradient', 'ticked'],
		titles: ['marquee', 'boxed', 'plate'],
		motion: ['sweep', 'slide-shutter', 'slam'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['display', 'condensed', 'retro'],
		bodyFontCategories: ['grotesk', 'sans', 'condensed'],
		palettes: ['sunrise', 'ember', 'neon', 'royal'],
		arcs: ['rapid-list', 'countdown', 'poster-series', 'hook-drop'],
	},
	'glitch-signal': {
		label: 'Glitch Signal',
		backgrounds: ['crt-glow', 'vhs-tracking', 'trace-lines', 'noir-fade'],
		layouts: ['full-bleed', 'lower-third', 'centered'],
		typography: ['technical', 'mono-terminal', 'pixel-arcade'],
		accents: ['bar-code', 'measure-marks', 'crosshair', 'sparks'],
		finishes: ['neon', 'noir', 'chrome'],
		cameras: ['handheld', 'still', 'push-in'],
		transitions: ['hard-cut', 'kinetic', 'punch-cut'],
		sfx: ['digital', 'crisp'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'dashed', 'zigzag'],
		titles: ['ghost', 'outline', 'tag'],
		motion: ['glitch', 'slide-shutter', 'zoom-punch'],
		tempo: [1.08, 1.12, 1.16],
		displayFontCategories: ['tech', 'mono', 'pixel', 'condensed'],
		bodyFontCategories: ['mono', 'tech'],
		palettes: ['neon', 'midnight', 'mono', 'slate'],
		arcs: ['myth-bust', 'hot-take', 'beat-drop', 'diagnostic'],
	},

	/* ---- Broadcast and screen ------------------------------------------- */
	'broadcast-strip': {
		label: 'Broadcast Strip',
		backgrounds: ['duotone-split', 'vertical-fade', 'cinematic-bands', 'corner-glow'],
		layouts: ['banner-top', 'wide-stage', 'editorial-left', 'lower-third'],
		typography: ['condensed-stack', 'technical', 'poster'],
		accents: ['blocks', 'slashes', 'frames', 'chevrons'],
		finishes: ['clean', 'matte', 'film'],
		cameras: ['still', 'drift', 'crane'],
		transitions: ['directional', 'graphic-wipe'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['bar', 'double', 'gradient'],
		titles: ['boxed', 'sidebar', 'stack', 'plate'],
		motion: ['slide-shutter', 'sweep', 'rise'],
		tempo: [0.96, 1, 1.04, 1.08],
		displayFontCategories: ['condensed', 'grotesk', 'tech'],
		bodyFontCategories: ['sans', 'grotesk', 'condensed'],
		palettes: ['azure', 'slate', 'mono', 'midnight'],
		arcs: ['newsroom', 'briefing', 'thesis-proof', 'index-cards'],
	},
	'sports-ticker': {
		label: 'Sports Ticker',
		backgrounds: ['stripe-march', 'duotone-split', 'corner-glow', 'hex-scatter'],
		layouts: ['ticker-frame', 'lower-third', 'banner-top', 'quadrant'],
		typography: ['condensed-stack', 'stencil-industrial', 'poster'],
		accents: ['chevrons', 'slashes', 'blocks', 'bar-code'],
		finishes: ['clean', 'chrome', 'neon'],
		cameras: ['drift', 'push-in', 'crane'],
		transitions: ['directional', 'punch-cut', 'kinetic'],
		sfx: ['digital', 'crisp'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['bar', 'ticked', 'gradient'],
		titles: ['boxed', 'plate', 'marquee'],
		motion: ['slam', 'slide-shutter', 'zoom-punch'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['condensed', 'display', 'tech'],
		bodyFontCategories: ['condensed', 'grotesk', 'tech'],
		palettes: ['ember', 'azure', 'midnight', 'neon'],
		arcs: ['countdown', 'scoreboard', 'rapid-list', 'beat-drop'],
	},
	'newsroom-lower': {
		label: 'Newsroom Lower',
		backgrounds: ['cinematic-bands', 'vertical-fade', 'flat-field', 'concrete-slab'],
		layouts: ['lower-third', 'banner-top', 'wide-stage'],
		typography: ['grotesk-tight', 'condensed-stack', 'technical'],
		accents: ['blocks', 'measure-marks', 'corner-ticks'],
		finishes: ['clean', 'matte', 'glass'],
		cameras: ['still', 'drift'],
		transitions: ['directional', 'dissolve', 'clock'],
		sfx: ['crisp', 'minimal'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['bar', 'double'],
		titles: ['plate', 'boxed', 'sidebar'],
		motion: ['sweep', 'rise', 'slide-shutter'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['grotesk', 'condensed', 'sans'],
		bodyFontCategories: ['sans', 'grotesk'],
		palettes: ['azure', 'slate', 'arctic', 'mono'],
		arcs: ['newsroom', 'briefing', 'explainer', 'thesis-proof'],
	},
	'documentary-slate': {
		label: 'Documentary Slate',
		backgrounds: ['noir-fade', 'cinematic-bands', 'ink-bloom', 'vertical-fade'],
		layouts: ['wide-stage', 'lower-third', 'centered'],
		typography: ['cinematic', 'editorial', 'serif-luxe'],
		accents: ['none', 'frames', 'corner-ticks'],
		finishes: ['film', 'noir', 'matte'],
		cameras: ['drift', 'crane', 'pull-out'],
		transitions: ['dissolve', 'iris'],
		sfx: ['cinematic', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['thin', 'bar', 'none'],
		titles: ['stack', 'bookend', 'ghost'],
		motion: ['blur-in', 'rise', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'condensed', 'grotesk'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['heritage', 'midnight', 'slate', 'mono'],
		arcs: ['chronicle', 'three-act', 'long-read', 'archive-dig'],
	},
	'cinema-bars': {
		label: 'Cinema Bars',
		backgrounds: ['cinematic-bands', 'noir-fade', 'spotlight', 'nebula-drift'],
		layouts: ['wide-stage', 'full-bleed', 'centered'],
		typography: ['cinematic', 'poster', 'wide-track'],
		accents: ['halo', 'none', 'starfield'],
		finishes: ['film', 'luminous', 'noir'],
		cameras: ['dolly', 'crane', 'push-in'],
		transitions: ['dissolve', 'iris', 'mixed'],
		sfx: ['cinematic'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['thin', 'none', 'gradient'],
		titles: ['stack', 'ghost', 'inline'],
		motion: ['blur-in', 'scale-fade', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92, 0.96],
		displayFontCategories: ['serif', 'display', 'condensed'],
		bodyFontCategories: ['sans', 'serif', 'grotesk'],
		palettes: ['midnight', 'slate', 'heritage', 'royal'],
		arcs: ['three-act', 'cold-open', 'chronicle', 'reveal'],
	},
	'title-sequence': {
		label: 'Title Sequence',
		backgrounds: ['noir-fade', 'liquid-chrome', 'halo-sweep', 'nebula-drift'],
		layouts: ['centered', 'full-bleed', 'baseline-drop'],
		typography: ['cinematic', 'wide-track', 'serif-luxe'],
		accents: ['halo', 'orbits', 'starfield', 'none'],
		finishes: ['bloom', 'chrome', 'film'],
		cameras: ['dolly', 'push-in', 'pull-out'],
		transitions: ['dissolve', 'iris', 'clock'],
		sfx: ['cinematic', 'minimal'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['thin', 'gradient', 'none'],
		titles: ['ghost', 'stack', 'outline'],
		motion: ['mask-reveal', 'blur-in', 'scale-fade', 'spin-in'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'display', 'condensed', 'grotesk'],
		bodyFontCategories: ['sans', 'grotesk', 'serif'],
		palettes: ['midnight', 'royal', 'mono', 'slate'],
		arcs: ['cold-open', 'reveal', 'three-act', 'manifesto'],
	},
	'terminal-log': {
		label: 'Terminal Log',
		backgrounds: ['flat-field', 'crt-glow', 'trace-lines', 'halftone-drift'],
		layouts: ['editorial-left', 'lower-third', 'margin-note'],
		typography: ['mono-terminal', 'technical', 'pixel-arcade'],
		accents: ['measure-marks', 'bar-code', 'crosshair', 'none'],
		finishes: ['neon', 'matte', 'noir'],
		cameras: ['still', 'drift'],
		transitions: ['hard-cut', 'directional'],
		sfx: ['digital', 'minimal'],
		textCase: ['upper', 'sentence'],
		corners: ['sharp'],
		rules: ['dashed', 'ticked', 'thin'],
		titles: ['tag', 'stack', 'bookend'],
		motion: ['typewriter', 'glitch', 'rise'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['mono', 'tech', 'pixel'],
		bodyFontCategories: ['mono', 'tech'],
		palettes: ['midnight', 'forest', 'mono', 'neon'],
		arcs: ['diagnostic', 'field-notes', 'explainer', 'briefing'],
	},

	/* ---- Minimal and luxury --------------------------------------------- */
	'minimal-air': {
		label: 'Minimal Air',
		backgrounds: ['flat-field', 'vertical-fade', 'soft-orbits', 'paper-wash'],
		layouts: ['centered', 'column-right', 'editorial-left', 'pillar-center'],
		typography: ['editorial', 'poster', 'serif-luxe', 'geometric-round'],
		accents: ['none', 'halo', 'arcs'],
		finishes: ['clean', 'matte', 'glass'],
		cameras: ['still', 'drift'],
		transitions: ['dissolve', 'directional'],
		sfx: ['minimal', 'organic'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'pill'],
		rules: ['thin', 'none', 'gradient'],
		titles: ['stack', 'underline', 'inline'],
		motion: ['rise', 'scale-fade', 'blur-in'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['sans', 'grotesk', 'serif', 'rounded'],
		bodyFontCategories: ['sans', 'grotesk', 'rounded'],
		palettes: ['arctic', 'paper', 'mono', 'azure'],
		arcs: ['thesis-proof', 'reveal', 'explainer', 'three-act'],
	},
	'luxe-serif': {
		label: 'Luxe Serif',
		backgrounds: ['noir-fade', 'vertical-fade', 'holo-foil', 'ink-bloom'],
		layouts: ['centered', 'pillar-center', 'cover-stack'],
		typography: ['serif-luxe', 'wide-track', 'editorial'],
		accents: ['none', 'frames', 'halo', 'orbits'],
		finishes: ['luminous', 'chrome', 'matte'],
		cameras: ['drift', 'push-in', 'sway'],
		transitions: ['dissolve', 'iris'],
		sfx: ['cinematic', 'minimal'],
		textCase: ['title', 'upper'],
		corners: ['sharp', 'soft'],
		rules: ['thin', 'double', 'gradient'],
		titles: ['bookend', 'stack', 'ghost'],
		motion: ['scale-fade', 'blur-in', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'display'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['royal', 'midnight', 'heritage', 'mono'],
		arcs: ['reveal', 'cold-open', 'three-act', 'lookbook'],
	},
	'gallery-frame': {
		label: 'Gallery Frame',
		backgrounds: ['flat-field', 'paper-wash', 'vertical-fade', 'concrete-slab'],
		layouts: ['centered', 'pillar-center', 'quadrant', 'magazine-grid'],
		typography: ['editorial', 'serif-luxe', 'wide-track'],
		accents: ['frames', 'none', 'corner-ticks'],
		finishes: ['matte', 'clean', 'paper'],
		cameras: ['still', 'drift'],
		transitions: ['dissolve', 'graphic-wipe', 'iris'],
		sfx: ['minimal', 'organic'],
		textCase: ['title', 'sentence'],
		corners: ['sharp'],
		rules: ['thin', 'bracket', 'none'],
		titles: ['bookend', 'stack', 'underline'],
		motion: ['mask-reveal', 'rise', 'scale-fade'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'sans', 'grotesk'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['paper', 'arctic', 'mono', 'heritage'],
		arcs: ['lookbook', 'index-cards', 'reveal', 'poster-series'],
	},
	'glass-panel': {
		label: 'Glass Panel',
		backgrounds: ['gradient-mesh', 'soft-orbits', 'aurora', 'aurora-veil'],
		layouts: ['centered', 'quadrant', 'gutter-right', 'cover-stack'],
		typography: ['geometric-round', 'poster', 'grotesk-tight'],
		accents: ['pills', 'halo', 'orbits', 'discs'],
		finishes: ['glass', 'clean', 'bloom'],
		cameras: ['drift', 'sway', 'push-in'],
		transitions: ['dissolve', 'directional', 'card-flip'],
		sfx: ['digital', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'pill'],
		rules: ['gradient', 'thin', 'none'],
		titles: ['plate', 'stack', 'boxed'],
		motion: ['scale-fade', 'rise', 'blur-in'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['sans', 'grotesk', 'rounded'],
		bodyFontCategories: ['sans', 'rounded', 'grotesk'],
		palettes: ['arctic', 'azure', 'royal', 'midnight'],
		arcs: ['product-tour', 'explainer', 'thesis-proof', 'reveal'],
	},
	'monolith-mono': {
		label: 'Monolith Mono',
		backgrounds: ['flat-field', 'concrete-slab', 'noir-fade', 'editorial-slab'],
		layouts: ['pillar-center', 'centered', 'baseline-drop'],
		typography: ['brutalist', 'wide-track', 'grotesk-tight'],
		accents: ['none', 'measure-marks', 'blocks'],
		finishes: ['matte', 'noir', 'clean'],
		cameras: ['still', 'push-in'],
		transitions: ['hard-cut', 'graphic-wipe'],
		sfx: ['minimal', 'cinematic'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['bar', 'none'],
		titles: ['stack', 'cutout', 'ghost'],
		motion: ['slam', 'mask-reveal', 'scale-fade'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['grotesk', 'condensed', 'sans'],
		bodyFontCategories: ['grotesk', 'mono', 'sans'],
		palettes: ['mono', 'slate', 'midnight', 'arctic'],
		arcs: ['manifesto', 'thesis-proof', 'reveal', 'cold-open'],
	},
	'ivory-studio': {
		label: 'Ivory Studio',
		backgrounds: ['paper-wash', 'flat-field', 'soft-orbits', 'terrazzo'],
		layouts: ['magazine-grid', 'centered', 'gutter-right'],
		typography: ['geometric-round', 'editorial', 'serif-luxe'],
		accents: ['discs', 'none', 'pills'],
		finishes: ['clean', 'paper', 'matte'],
		cameras: ['still', 'drift', 'sway'],
		transitions: ['dissolve', 'card-flip'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['pill', 'soft'],
		rules: ['thin', 'gradient', 'none'],
		titles: ['stack', 'plate', 'underline'],
		motion: ['rise', 'elastic', 'scale-fade'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['rounded', 'sans', 'serif'],
		bodyFontCategories: ['rounded', 'sans', 'serif'],
		palettes: ['paper', 'arctic', 'sunrise', 'mono'],
		arcs: ['lookbook', 'product-tour', 'explainer', 'index-cards'],
	},

	/* ---- Neon, retro and arcade ----------------------------------------- */
	'neon-arcade': {
		label: 'Neon Arcade',
		backgrounds: ['spotlight', 'gradient-mesh', 'halo-sweep', 'trace-lines'],
		layouts: ['centered', 'full-bleed', 'poster', 'quadrant'],
		typography: ['technical', 'poster', 'pixel-arcade'],
		accents: ['sparks', 'halo', 'rings', 'starfield'],
		finishes: ['neon', 'luminous', 'bloom'],
		cameras: ['orbit', 'dolly', 'push-in'],
		transitions: ['kinetic', 'mixed', 'punch-cut'],
		sfx: ['digital', 'crisp'],
		textCase: ['upper'],
		corners: ['pill', 'soft'],
		rules: ['gradient', 'bar', 'ticked'],
		titles: ['outline', 'inline', 'ghost'],
		motion: ['zoom-punch', 'glitch', 'elastic'],
		tempo: [1.04, 1.08, 1.12, 1.16],
		displayFontCategories: ['tech', 'display', 'pixel', 'grotesk'],
		bodyFontCategories: ['tech', 'mono', 'grotesk'],
		palettes: ['neon', 'midnight', 'royal', 'ember'],
		arcs: ['beat-drop', 'countdown', 'hook-drop', 'rapid-list'],
	},
	'synthwave-grid': {
		label: 'Synthwave Grid',
		backgrounds: ['drafting-wash', 'nebula-drift', 'sunburst-rays', 'gradient-mesh'],
		layouts: ['centered', 'full-bleed', 'baseline-drop'],
		typography: ['display-swash', 'technical', 'wide-track'],
		accents: ['measure-marks', 'starfield', 'halo', 'orbits'],
		finishes: ['neon', 'bloom', 'chrome'],
		cameras: ['dolly', 'crane', 'push-in'],
		transitions: ['kinetic', 'iris', 'mixed'],
		sfx: ['digital', 'cinematic'],
		textCase: ['upper'],
		corners: ['sharp', 'pill'],
		rules: ['gradient', 'bar'],
		titles: ['outline', 'ghost', 'marquee'],
		motion: ['zoom-punch', 'scale-fade', 'spin-in'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['display', 'tech', 'retro'],
		bodyFontCategories: ['tech', 'mono', 'grotesk'],
		palettes: ['neon', 'midnight', 'royal', 'ember'],
		arcs: ['beat-drop', 'reveal', 'cold-open', 'countdown'],
	},
	'pixel-quest': {
		label: 'Pixel Quest',
		backgrounds: ['halftone-drift', 'confetti-field', 'flat-field', 'drafting-wash'],
		layouts: ['quadrant', 'centered', 'ticker-frame'],
		typography: ['pixel-arcade', 'technical', 'comic-punch'],
		accents: ['blocks', 'measure-marks', 'sparks', 'hex-cluster'],
		finishes: ['clean', 'neon', 'matte'],
		cameras: ['still', 'sway'],
		transitions: ['hard-cut', 'graphic-wipe', 'punch-cut'],
		sfx: ['digital', 'crisp'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'dashed', 'bar'],
		titles: ['boxed', 'tag', 'plate'],
		motion: ['stagger-drop', 'slam', 'slide-shutter'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['pixel', 'tech', 'display'],
		bodyFontCategories: ['pixel', 'mono', 'tech'],
		palettes: ['neon', 'forest', 'midnight', 'sunrise'],
		arcs: ['countdown', 'rapid-list', 'explainer', 'scoreboard'],
	},
	'retro-motel': {
		label: 'Retro Motel',
		backgrounds: ['sunburst-rays', 'stripe-march', 'terrazzo', 'risograph'],
		layouts: ['centered', 'poster', 'cover-stack'],
		typography: ['display-swash', 'ransom-cut', 'comic-punch'],
		accents: ['starfield', 'discs', 'waves', 'pills'],
		finishes: ['riso', 'print', 'bloom'],
		cameras: ['sway', 'drift'],
		transitions: ['graphic-wipe', 'clock', 'card-flip'],
		sfx: ['organic', 'crisp'],
		textCase: ['upper', 'title'],
		corners: ['pill', 'soft'],
		rules: ['double', 'zigzag', 'bar'],
		titles: ['marquee', 'boxed', 'shadowbox'],
		motion: ['elastic', 'spin-in', 'stagger-drop'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['retro', 'display', 'script'],
		bodyFontCategories: ['sans', 'retro', 'grotesk'],
		palettes: ['sunrise', 'ember', 'heritage', 'paper'],
		arcs: ['lookbook', 'scrapbook', 'poster-series', 'hook-drop'],
	},
	'vhs-rewind': {
		label: 'VHS Rewind',
		backgrounds: ['vhs-tracking', 'crt-glow', 'noir-fade', 'liquid-chrome'],
		layouts: ['full-bleed', 'lower-third', 'centered'],
		typography: ['technical', 'display-swash', 'mono-terminal'],
		accents: ['bar-code', 'measure-marks', 'crosshair'],
		finishes: ['film', 'noir', 'neon'],
		cameras: ['handheld', 'drift'],
		transitions: ['hard-cut', 'kinetic', 'clock'],
		sfx: ['digital', 'cinematic'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'dashed'],
		titles: ['tag', 'ghost', 'shadowbox'],
		motion: ['glitch', 'slide-shutter', 'blur-in'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['tech', 'display', 'condensed'],
		bodyFontCategories: ['mono', 'tech', 'sans'],
		palettes: ['midnight', 'neon', 'ember', 'slate'],
		arcs: ['archive-dig', 'chronicle', 'hot-take', 'cold-open'],
	},
	'chrome-heat': {
		label: 'Chrome Heat',
		backgrounds: ['liquid-chrome', 'holo-foil', 'gradient-mesh', 'nebula-drift'],
		layouts: ['centered', 'pillar-center', 'full-bleed'],
		typography: ['display-swash', 'wide-track', 'brutalist'],
		accents: ['orbits', 'halo', 'rings', 'waves'],
		finishes: ['chrome', 'bloom', 'luminous'],
		cameras: ['orbit', 'push-in', 'sway'],
		transitions: ['iris', 'card-flip', 'mixed'],
		sfx: ['digital', 'cinematic'],
		textCase: ['upper'],
		corners: ['pill', 'sharp'],
		rules: ['gradient', 'none'],
		titles: ['ghost', 'outline', 'shadowbox'],
		motion: ['spin-in', 'zoom-punch', 'scale-fade'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['display', 'grotesk', 'tech'],
		bodyFontCategories: ['grotesk', 'sans', 'tech'],
		palettes: ['royal', 'midnight', 'neon', 'slate'],
		arcs: ['reveal', 'product-tour', 'beat-drop', 'lookbook'],
	},
	'pop-sticker': {
		label: 'Pop Sticker',
		backgrounds: ['flat-field', 'confetti-field', 'terrazzo', 'halftone-drift'],
		layouts: ['centered', 'quadrant', 'offset-stack'],
		typography: ['comic-punch', 'friendly', 'geometric-round'],
		accents: ['discs', 'sparks', 'triangles', 'pills'],
		finishes: ['clean', 'riso', 'bloom'],
		cameras: ['sway', 'still'],
		transitions: ['punch-cut', 'card-flip', 'kinetic'],
		sfx: ['crisp', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['pill', 'soft'],
		rules: ['zigzag', 'dotted', 'bar'],
		titles: ['shadowbox', 'boxed', 'tag'],
		motion: ['elastic', 'stagger-drop', 'spin-in'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['comic', 'display', 'rounded'],
		bodyFontCategories: ['rounded', 'sans', 'comic'],
		palettes: ['sunrise', 'neon', 'ember', 'azure'],
		arcs: ['rapid-list', 'hook-drop', 'explainer', 'myth-bust'],
	},
	'comic-panel': {
		label: 'Comic Panel',
		backgrounds: ['halftone-drift', 'sunburst-rays', 'flat-field', 'risograph'],
		layouts: ['quadrant', 'magazine-grid', 'corner-anchor'],
		typography: ['comic-punch', 'ransom-cut', 'brutalist'],
		accents: ['triangles', 'sparks', 'blocks', 'chevrons'],
		finishes: ['print', 'riso', 'clean'],
		cameras: ['still', 'handheld'],
		transitions: ['graphic-wipe', 'punch-cut', 'hard-cut'],
		sfx: ['crisp', 'organic'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['zigzag', 'bar', 'ticked'],
		titles: ['boxed', 'shadowbox', 'cutout'],
		motion: ['slam', 'stagger-drop', 'elastic'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['comic', 'display', 'retro'],
		bodyFontCategories: ['comic', 'sans', 'condensed'],
		palettes: ['sunrise', 'ember', 'neon', 'paper'],
		arcs: ['scrapbook', 'three-act', 'rapid-list', 'myth-bust'],
	},

	/* ---- Data and business ---------------------------------------------- */
	'data-brief': {
		label: 'Data Brief',
		backgrounds: ['flat-field', 'drafting-wash', 'editorial-slab', 'vertical-fade'],
		layouts: ['magazine-grid', 'wide-stage', 'editorial-left', 'quadrant'],
		typography: ['technical', 'grotesk-tight', 'condensed-stack'],
		accents: ['measure-marks', 'blocks', 'none'],
		finishes: ['clean', 'matte', 'glass'],
		cameras: ['still', 'drift'],
		transitions: ['directional', 'dissolve', 'clock'],
		sfx: ['digital', 'minimal'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['bar', 'thin', 'ticked'],
		titles: ['sidebar', 'plate', 'stack'],
		motion: ['rise', 'stagger-drop', 'sweep'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['grotesk', 'condensed', 'tech', 'sans'],
		bodyFontCategories: ['sans', 'mono', 'grotesk'],
		palettes: ['azure', 'arctic', 'slate', 'mono'],
		arcs: ['data-story', 'briefing', 'thesis-proof', 'scoreboard'],
	},
	'boardroom-deck': {
		label: 'Boardroom Deck',
		backgrounds: ['vertical-fade', 'flat-field', 'concrete-slab', 'editorial-slab'],
		layouts: ['magazine-grid', 'gutter-right', 'wide-stage'],
		typography: ['grotesk-tight', 'editorial', 'geometric-round'],
		accents: ['none', 'measure-marks', 'corner-ticks'],
		finishes: ['clean', 'matte'],
		cameras: ['still', 'drift'],
		transitions: ['directional', 'dissolve'],
		sfx: ['minimal', 'crisp'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'sharp'],
		rules: ['thin', 'bar', 'gradient'],
		titles: ['sidebar', 'stack', 'plate'],
		motion: ['rise', 'sweep', 'scale-fade'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['grotesk', 'sans', 'serif'],
		bodyFontCategories: ['sans', 'grotesk'],
		palettes: ['azure', 'slate', 'arctic', 'royal'],
		arcs: ['briefing', 'data-story', 'thesis-proof', 'roadmap'],
	},
	'fintech-ledger': {
		label: 'Fintech Ledger',
		backgrounds: ['drafting-wash', 'hex-scatter', 'flat-field', 'trace-lines'],
		layouts: ['quadrant', 'magazine-grid', 'lower-third'],
		typography: ['technical', 'mono-terminal', 'grotesk-tight'],
		accents: ['measure-marks', 'hex-cluster', 'bar-code'],
		finishes: ['glass', 'clean', 'neon'],
		cameras: ['still', 'push-in', 'drift'],
		transitions: ['directional', 'clock', 'card-flip'],
		sfx: ['digital', 'minimal'],
		textCase: ['upper'],
		corners: ['sharp', 'soft'],
		rules: ['ticked', 'thin', 'gradient'],
		titles: ['plate', 'tag', 'sidebar'],
		motion: ['stagger-drop', 'rise', 'typewriter'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['tech', 'grotesk', 'mono'],
		bodyFontCategories: ['mono', 'tech', 'sans'],
		palettes: ['midnight', 'forest', 'azure', 'slate'],
		arcs: ['data-story', 'diagnostic', 'briefing', 'scoreboard'],
	},
	'infographic-flat': {
		label: 'Infographic Flat',
		backgrounds: ['flat-field', 'halftone-drift', 'terrazzo', 'stripe-march'],
		layouts: ['quadrant', 'magazine-grid', 'centered'],
		typography: ['geometric-round', 'friendly', 'poster'],
		accents: ['discs', 'pills', 'blocks', 'waves'],
		finishes: ['clean', 'riso', 'matte'],
		cameras: ['still', 'sway'],
		transitions: ['graphic-wipe', 'card-flip', 'directional'],
		sfx: ['crisp', 'digital'],
		textCase: ['title', 'upper'],
		corners: ['pill', 'soft'],
		rules: ['bar', 'dotted', 'gradient'],
		titles: ['plate', 'boxed', 'stack'],
		motion: ['stagger-drop', 'elastic', 'rise'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['rounded', 'sans', 'grotesk', 'display'],
		bodyFontCategories: ['rounded', 'sans', 'grotesk'],
		palettes: ['azure', 'sunrise', 'arctic', 'forest'],
		arcs: ['explainer', 'data-story', 'rapid-list', 'how-to'],
	},
	'blueprint-tech': {
		label: 'Blueprint Tech',
		backgrounds: ['drafting-wash', 'iso-shards', 'trace-lines', 'hex-scatter'],
		layouts: ['wide-stage', 'quadrant', 'margin-note'],
		typography: ['technical', 'mono-terminal', 'stencil-industrial'],
		accents: ['measure-marks', 'crosshair', 'corner-ticks', 'hex-cluster'],
		finishes: ['matte', 'glass', 'clean'],
		cameras: ['drift', 'crane', 'still'],
		transitions: ['directional', 'graphic-wipe', 'clock'],
		sfx: ['digital', 'minimal'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'dashed', 'bracket'],
		titles: ['tag', 'bookend', 'sidebar'],
		motion: ['mask-reveal', 'typewriter', 'rise'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['tech', 'condensed', 'mono'],
		bodyFontCategories: ['mono', 'tech', 'sans'],
		palettes: ['azure', 'midnight', 'slate', 'arctic'],
		arcs: ['how-to', 'diagnostic', 'explainer', 'roadmap'],
	},
	'startup-pitch': {
		label: 'Startup Pitch',
		backgrounds: ['gradient-mesh', 'corner-glow', 'soft-orbits', 'aurora'],
		layouts: ['centered', 'gutter-right', 'cover-stack'],
		typography: ['grotesk-tight', 'geometric-round', 'poster'],
		accents: ['halo', 'pills', 'discs', 'orbits'],
		finishes: ['glass', 'bloom', 'clean'],
		cameras: ['push-in', 'drift', 'sway'],
		transitions: ['directional', 'punch-cut', 'card-flip'],
		sfx: ['digital', 'crisp'],
		textCase: ['title', 'upper'],
		corners: ['pill', 'soft'],
		rules: ['gradient', 'bar', 'none'],
		titles: ['plate', 'stack', 'boxed'],
		motion: ['rise', 'zoom-punch', 'elastic'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['grotesk', 'sans', 'display', 'rounded'],
		bodyFontCategories: ['sans', 'grotesk', 'rounded'],
		palettes: ['royal', 'azure', 'neon', 'midnight'],
		arcs: ['product-tour', 'thesis-proof', 'hook-drop', 'roadmap'],
	},
	'scoreboard-live': {
		label: 'Scoreboard Live',
		backgrounds: ['hex-scatter', 'stripe-march', 'drafting-wash', 'corner-glow'],
		layouts: ['quadrant', 'ticker-frame', 'banner-top'],
		typography: ['stencil-industrial', 'condensed-stack', 'technical'],
		accents: ['chevrons', 'hex-cluster', 'bar-code', 'measure-marks'],
		finishes: ['chrome', 'neon', 'clean'],
		cameras: ['push-in', 'crane', 'still'],
		transitions: ['punch-cut', 'directional', 'clock'],
		sfx: ['digital', 'crisp'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'bar', 'gradient'],
		titles: ['plate', 'boxed', 'marquee'],
		motion: ['slam', 'stagger-drop', 'slide-shutter'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['condensed', 'tech', 'display'],
		bodyFontCategories: ['tech', 'condensed', 'mono'],
		palettes: ['ember', 'midnight', 'azure', 'neon'],
		arcs: ['scoreboard', 'countdown', 'data-story', 'rapid-list'],
	},

	/* ---- Story, travel and nature --------------------------------------- */
	'story-cards': {
		label: 'Story Cards',
		backgrounds: ['soft-orbits', 'vertical-fade', 'paper-wash', 'aurora'],
		layouts: ['centered', 'offset-stack', 'cover-stack'],
		typography: ['friendly', 'editorial', 'geometric-round'],
		accents: ['discs', 'halo', 'pills', 'none'],
		finishes: ['clean', 'matte', 'bloom'],
		cameras: ['drift', 'sway', 'still'],
		transitions: ['dissolve', 'card-flip', 'directional'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'pill'],
		rules: ['thin', 'dotted', 'gradient'],
		titles: ['stack', 'plate', 'underline'],
		motion: ['rise', 'elastic', 'scale-fade'],
		tempo: [0.88, 0.92, 0.96, 1],
		displayFontCategories: ['rounded', 'sans', 'serif', 'handwriting'],
		bodyFontCategories: ['rounded', 'sans', 'serif'],
		palettes: ['sunrise', 'paper', 'arctic', 'forest'],
		arcs: ['three-act', 'scrapbook', 'explainer', 'lookbook'],
	},
	'expedition-log': {
		label: 'Expedition Log',
		backgrounds: ['topographic', 'sand-dunes', 'paper-wash', 'ink-bloom'],
		layouts: ['editorial-left', 'margin-note', 'wide-stage'],
		typography: ['stencil-industrial', 'technical', 'editorial'],
		accents: ['crosshair', 'corner-ticks', 'measure-marks', 'waves'],
		finishes: ['paper', 'film', 'matte'],
		cameras: ['drift', 'crane', 'handheld'],
		transitions: ['dissolve', 'graphic-wipe', 'iris'],
		sfx: ['organic', 'cinematic'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['dashed', 'ticked', 'bracket'],
		titles: ['tag', 'bookend', 'sidebar'],
		motion: ['mask-reveal', 'rise', 'typewriter'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['condensed', 'serif', 'display'],
		bodyFontCategories: ['sans', 'mono', 'serif'],
		palettes: ['heritage', 'forest', 'ember', 'paper'],
		arcs: ['field-notes', 'chronicle', 'archive-dig', 'three-act'],
	},
	'atlas-route': {
		label: 'Atlas Route',
		backgrounds: ['topographic', 'drafting-wash', 'vertical-fade', 'iso-shards'],
		layouts: ['wide-stage', 'magazine-grid', 'lower-third'],
		typography: ['technical', 'condensed-stack', 'grotesk-tight'],
		accents: ['measure-marks', 'crosshair', 'orbits'],
		finishes: ['matte', 'clean', 'paper'],
		cameras: ['crane', 'drift', 'pull-out'],
		transitions: ['directional', 'clock', 'dissolve'],
		sfx: ['minimal', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['ticked', 'thin', 'dashed'],
		titles: ['sidebar', 'tag', 'stack'],
		motion: ['sweep', 'mask-reveal', 'stagger-drop'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['condensed', 'grotesk', 'tech'],
		bodyFontCategories: ['sans', 'grotesk', 'mono'],
		palettes: ['arctic', 'azure', 'forest', 'heritage'],
		arcs: ['journey', 'chronicle', 'explainer', 'roadmap'],
	},
	'botanical-press': {
		label: 'Botanical Press',
		backgrounds: ['paper-wash', 'ink-bloom', 'terrazzo', 'soft-orbits'],
		layouts: ['centered', 'magazine-grid', 'pillar-center'],
		typography: ['serif-luxe', 'editorial', 'handwritten'],
		accents: ['none', 'frames', 'waves', 'discs'],
		finishes: ['paper', 'print', 'matte'],
		cameras: ['still', 'drift', 'sway'],
		transitions: ['dissolve', 'iris'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'sharp'],
		rules: ['thin', 'dotted', 'bracket'],
		titles: ['bookend', 'underline', 'stack'],
		motion: ['blur-in', 'rise', 'scale-fade'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'script', 'handwriting'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['forest', 'paper', 'heritage', 'sunrise'],
		arcs: ['field-notes', 'lookbook', 'long-read', 'explainer'],
	},
	'monsoon-ink': {
		label: 'Monsoon Ink',
		backgrounds: ['ink-bloom', 'ripple-rings', 'vertical-fade', 'aurora-veil'],
		layouts: ['centered', 'editorial-left', 'cover-stack'],
		typography: ['serif-luxe', 'handwritten', 'editorial'],
		accents: ['waves', 'ribbons', 'none', 'halo'],
		finishes: ['film', 'paper', 'bloom'],
		cameras: ['drift', 'sway', 'pull-out'],
		transitions: ['dissolve', 'iris', 'mixed'],
		sfx: ['organic', 'cinematic'],
		textCase: ['title', 'sentence'],
		corners: ['soft'],
		rules: ['thin', 'gradient', 'none'],
		titles: ['ghost', 'stack', 'bookend'],
		motion: ['blur-in', 'mask-reveal', 'scale-fade'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'script', 'devanagari'],
		bodyFontCategories: ['serif', 'sans', 'devanagari'],
		palettes: ['heritage', 'forest', 'royal', 'slate'],
		arcs: ['chronicle', 'three-act', 'long-read', 'journey'],
	},
	'summit-parallax': {
		label: 'Summit Parallax',
		backgrounds: ['topographic', 'vertical-fade', 'aurora-veil', 'sand-dunes'],
		layouts: ['wide-stage', 'full-bleed', 'lower-third'],
		typography: ['cinematic', 'condensed-stack', 'wide-track'],
		accents: ['none', 'halo', 'waves', 'corner-ticks'],
		finishes: ['film', 'luminous', 'matte'],
		cameras: ['crane', 'dolly', 'pull-out'],
		transitions: ['dissolve', 'iris', 'directional'],
		sfx: ['cinematic', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['thin', 'bar', 'none'],
		titles: ['stack', 'ghost', 'bookend'],
		motion: ['mask-reveal', 'blur-in', 'rise'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['condensed', 'serif', 'grotesk'],
		bodyFontCategories: ['sans', 'grotesk', 'serif'],
		palettes: ['arctic', 'midnight', 'heritage', 'slate'],
		arcs: ['journey', 'cold-open', 'three-act', 'reveal'],
	},
	'desert-dusk': {
		label: 'Desert Dusk',
		backgrounds: ['sand-dunes', 'sunburst-rays', 'vertical-fade', 'nebula-drift'],
		layouts: ['wide-stage', 'centered', 'baseline-drop'],
		typography: ['wide-track', 'cinematic', 'serif-luxe'],
		accents: ['halo', 'waves', 'starfield', 'none'],
		finishes: ['film', 'bloom', 'luminous'],
		cameras: ['pull-out', 'drift', 'crane'],
		transitions: ['dissolve', 'iris'],
		sfx: ['cinematic', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['sharp', 'soft'],
		rules: ['gradient', 'thin', 'none'],
		titles: ['ghost', 'stack', 'bookend'],
		motion: ['blur-in', 'scale-fade', 'mask-reveal'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'display', 'condensed'],
		bodyFontCategories: ['serif', 'sans'],
		palettes: ['ember', 'sunrise', 'heritage', 'midnight'],
		arcs: ['journey', 'cold-open', 'reveal', 'chronicle'],
	},
	'oceanic-drift': {
		label: 'Oceanic Drift',
		backgrounds: ['ripple-rings', 'aurora-veil', 'gradient-mesh', 'soft-orbits'],
		layouts: ['centered', 'full-bleed', 'pillar-center'],
		typography: ['geometric-round', 'wide-track', 'friendly'],
		accents: ['waves', 'rings', 'orbits', 'halo'],
		finishes: ['glass', 'bloom', 'luminous'],
		cameras: ['sway', 'drift', 'orbit'],
		transitions: ['dissolve', 'iris', 'card-flip'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['pill', 'soft'],
		rules: ['gradient', 'thin', 'none'],
		titles: ['plate', 'ghost', 'stack'],
		motion: ['scale-fade', 'blur-in', 'elastic'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['rounded', 'sans', 'grotesk'],
		bodyFontCategories: ['rounded', 'sans'],
		palettes: ['azure', 'arctic', 'forest', 'midnight'],
		arcs: ['journey', 'explainer', 'reveal', 'lookbook'],
	},

	/* ---- Culture, heritage and craft ------------------------------------ */
	'heritage-gold': {
		label: 'Heritage Gold',
		backgrounds: ['holo-foil', 'ink-bloom', 'noir-fade', 'concrete-slab'],
		layouts: ['centered', 'pillar-center', 'cover-stack'],
		typography: ['serif-luxe', 'display-swash', 'wide-track'],
		accents: ['frames', 'orbits', 'corner-ticks', 'halo'],
		finishes: ['chrome', 'luminous', 'print'],
		cameras: ['push-in', 'drift', 'sway'],
		transitions: ['dissolve', 'iris', 'clock'],
		sfx: ['cinematic', 'organic'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['double', 'bracket', 'thin'],
		titles: ['bookend', 'plate', 'ghost'],
		motion: ['mask-reveal', 'scale-fade', 'blur-in'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'display', 'devanagari'],
		bodyFontCategories: ['serif', 'sans', 'devanagari'],
		palettes: ['heritage', 'royal', 'ember', 'midnight'],
		arcs: ['chronicle', 'archive-dig', 'reveal', 'three-act'],
	},
	'temple-relief': {
		label: 'Temple Relief',
		backgrounds: ['concrete-slab', 'topographic', 'ink-bloom', 'terrazzo'],
		layouts: ['pillar-center', 'centered', 'wide-stage'],
		typography: ['stencil-industrial', 'serif-luxe', 'wide-track'],
		accents: ['frames', 'measure-marks', 'corner-ticks', 'hex-cluster'],
		finishes: ['matte', 'print', 'noir'],
		cameras: ['crane', 'push-in', 'still'],
		transitions: ['graphic-wipe', 'dissolve', 'clock'],
		sfx: ['organic', 'cinematic'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['double', 'bar', 'bracket'],
		titles: ['bookend', 'cutout', 'stack'],
		motion: ['mask-reveal', 'rise', 'slam'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['serif', 'condensed', 'devanagari'],
		bodyFontCategories: ['serif', 'sans', 'devanagari'],
		palettes: ['heritage', 'ember', 'slate', 'paper'],
		arcs: ['chronicle', 'archive-dig', 'journey', 'long-read'],
	},
	'festival-poster': {
		label: 'Festival Poster',
		backgrounds: ['sunburst-rays', 'kaleidoscope', 'risograph', 'terrazzo'],
		layouts: ['poster', 'centered', 'cover-stack'],
		typography: ['display-swash', 'poster', 'ransom-cut'],
		accents: ['starfield', 'triangles', 'discs', 'waves'],
		finishes: ['riso', 'bloom', 'print'],
		cameras: ['sway', 'push-in', 'orbit'],
		transitions: ['kinetic', 'clock', 'graphic-wipe'],
		sfx: ['organic', 'crisp'],
		textCase: ['upper'],
		corners: ['pill', 'sharp'],
		rules: ['zigzag', 'double', 'bar'],
		titles: ['marquee', 'cutout', 'shadowbox'],
		motion: ['spin-in', 'elastic', 'stagger-drop'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['display', 'retro', 'devanagari', 'script'],
		bodyFontCategories: ['sans', 'grotesk', 'devanagari'],
		palettes: ['ember', 'sunrise', 'royal', 'neon'],
		arcs: ['poster-series', 'countdown', 'hook-drop', 'lookbook'],
	},
	'craft-workshop': {
		label: 'Craft Workshop',
		backgrounds: ['paper-wash', 'concrete-slab', 'terrazzo', 'halftone-drift'],
		layouts: ['magazine-grid', 'editorial-left', 'quadrant'],
		typography: ['handwritten', 'editorial', 'friendly'],
		accents: ['none', 'corner-ticks', 'discs', 'waves'],
		finishes: ['paper', 'xerox', 'matte'],
		cameras: ['still', 'handheld', 'sway'],
		transitions: ['card-flip', 'dissolve', 'graphic-wipe'],
		sfx: ['organic', 'minimal'],
		textCase: ['title', 'sentence'],
		corners: ['soft', 'sharp'],
		rules: ['dotted', 'dashed', 'thin'],
		titles: ['tag', 'underline', 'stack'],
		motion: ['rise', 'stagger-drop', 'elastic'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['handwriting', 'serif', 'rounded'],
		bodyFontCategories: ['sans', 'handwriting', 'serif'],
		palettes: ['paper', 'heritage', 'forest', 'sunrise'],
		arcs: ['how-to', 'field-notes', 'scrapbook', 'explainer'],
	},
	'kitchen-table': {
		label: 'Kitchen Table',
		backgrounds: ['terrazzo', 'paper-wash', 'soft-orbits', 'confetti-field'],
		layouts: ['centered', 'quadrant', 'offset-stack'],
		typography: ['friendly', 'handwritten', 'geometric-round'],
		accents: ['discs', 'pills', 'waves', 'none'],
		finishes: ['clean', 'paper', 'bloom'],
		cameras: ['sway', 'still', 'drift'],
		transitions: ['card-flip', 'dissolve', 'punch-cut'],
		sfx: ['organic', 'crisp'],
		textCase: ['title', 'sentence'],
		corners: ['pill', 'soft'],
		rules: ['dotted', 'gradient', 'thin'],
		titles: ['plate', 'shadowbox', 'underline'],
		motion: ['elastic', 'rise', 'stagger-drop'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['rounded', 'handwriting', 'serif', 'display'],
		bodyFontCategories: ['rounded', 'sans', 'handwriting'],
		palettes: ['sunrise', 'paper', 'ember', 'forest'],
		arcs: ['how-to', 'rapid-list', 'explainer', 'lookbook'],
	},

	/* ---- Motion systems and abstract ------------------------------------ */
	'split-duo': {
		label: 'Split Duo',
		backgrounds: ['duotone-split', 'editorial-slab', 'stripe-march', 'confetti-field'],
		layouts: ['split-vertical', 'diagonal-split', 'quadrant'],
		typography: ['grotesk-tight', 'condensed-stack', 'brutalist'],
		accents: ['blocks', 'slashes', 'chevrons'],
		finishes: ['clean', 'matte', 'print'],
		cameras: ['still', 'push-in'],
		transitions: ['graphic-wipe', 'directional', 'hard-cut'],
		sfx: ['crisp', 'minimal'],
		textCase: ['upper', 'title'],
		corners: ['sharp'],
		rules: ['bar', 'double', 'none'],
		titles: ['sidebar', 'boxed', 'cutout'],
		motion: ['slide-shutter', 'slam', 'sweep'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['grotesk', 'condensed', 'sans'],
		bodyFontCategories: ['grotesk', 'sans', 'condensed'],
		palettes: ['mono', 'azure', 'ember', 'slate'],
		arcs: ['before-after', 'versus', 'thesis-proof', 'myth-bust'],
	},
	'diagonal-cut': {
		label: 'Diagonal Cut',
		backgrounds: ['duotone-split', 'stripe-march', 'corner-glow', 'liquid-chrome'],
		layouts: ['diagonal-split', 'corner-anchor', 'full-bleed'],
		typography: ['brutalist', 'poster', 'stencil-industrial'],
		accents: ['slashes', 'chevrons', 'triangles', 'blocks'],
		finishes: ['clean', 'chrome', 'neon'],
		cameras: ['push-in', 'sway', 'handheld'],
		transitions: ['graphic-wipe', 'punch-cut', 'kinetic'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['bar', 'zigzag', 'gradient'],
		titles: ['cutout', 'boxed', 'outline'],
		motion: ['slam', 'slide-shutter', 'zoom-punch'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['condensed', 'display', 'grotesk'],
		bodyFontCategories: ['grotesk', 'condensed', 'sans'],
		palettes: ['ember', 'neon', 'mono', 'royal'],
		arcs: ['versus', 'hook-drop', 'beat-drop', 'before-after'],
	},
	'isometric-build': {
		label: 'Isometric Build',
		backgrounds: ['iso-shards', 'drafting-wash', 'hex-scatter', 'halftone-drift'],
		layouts: ['wide-stage', 'quadrant', 'pillar-center'],
		typography: ['geometric-round', 'technical', 'grotesk-tight'],
		accents: ['hex-cluster', 'measure-marks', 'blocks', 'triangles'],
		finishes: ['clean', 'glass', 'matte'],
		cameras: ['crane', 'orbit', 'drift'],
		transitions: ['card-flip', 'directional', 'clock'],
		sfx: ['digital', 'crisp'],
		textCase: ['title', 'upper'],
		corners: ['soft', 'sharp'],
		rules: ['thin', 'ticked', 'gradient'],
		titles: ['plate', 'sidebar', 'stack'],
		motion: ['stagger-drop', 'spin-in', 'rise'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['rounded', 'grotesk', 'tech'],
		bodyFontCategories: ['sans', 'rounded', 'mono'],
		palettes: ['azure', 'arctic', 'royal', 'forest'],
		arcs: ['how-to', 'product-tour', 'roadmap', 'explainer'],
	},
	'orbit-system': {
		label: 'Orbit System',
		backgrounds: ['nebula-drift', 'soft-orbits', 'halo-sweep', 'aurora'],
		layouts: ['pillar-center', 'centered', 'full-bleed'],
		typography: ['wide-track', 'geometric-round', 'cinematic'],
		accents: ['orbits', 'rings', 'starfield', 'halo'],
		finishes: ['bloom', 'luminous', 'glass'],
		cameras: ['orbit', 'sway', 'pull-out'],
		transitions: ['iris', 'dissolve', 'clock'],
		sfx: ['cinematic', 'digital'],
		textCase: ['upper', 'title'],
		corners: ['pill', 'sharp'],
		rules: ['gradient', 'thin', 'none'],
		titles: ['ghost', 'plate', 'stack'],
		motion: ['spin-in', 'scale-fade', 'mask-reveal'],
		tempo: [0.88, 0.92, 0.96],
		displayFontCategories: ['grotesk', 'sans', 'display'],
		bodyFontCategories: ['sans', 'grotesk', 'tech'],
		palettes: ['midnight', 'royal', 'neon', 'slate'],
		arcs: ['reveal', 'cold-open', 'explainer', 'journey'],
	},
	'kaleido-bloom': {
		label: 'Kaleido Bloom',
		backgrounds: ['kaleidoscope', 'terrazzo', 'sunburst-rays', 'ripple-rings'],
		layouts: ['centered', 'pillar-center', 'quadrant'],
		typography: ['display-swash', 'geometric-round', 'poster'],
		accents: ['triangles', 'discs', 'waves', 'starfield'],
		finishes: ['bloom', 'riso', 'luminous'],
		cameras: ['orbit', 'sway', 'push-in'],
		transitions: ['clock', 'iris', 'kinetic'],
		sfx: ['organic', 'digital'],
		textCase: ['upper', 'title'],
		corners: ['pill', 'soft'],
		rules: ['zigzag', 'gradient', 'double'],
		titles: ['ghost', 'marquee', 'shadowbox'],
		motion: ['spin-in', 'elastic', 'scale-fade'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['display', 'rounded', 'retro'],
		bodyFontCategories: ['rounded', 'sans', 'grotesk'],
		palettes: ['sunrise', 'neon', 'royal', 'ember'],
		arcs: ['lookbook', 'beat-drop', 'poster-series', 'reveal'],
	},
	'shutter-grid': {
		label: 'Shutter Grid',
		backgrounds: ['confetti-field', 'stripe-march', 'flat-field', 'halftone-drift'],
		layouts: ['quadrant', 'magazine-grid', 'ticker-frame'],
		typography: ['grotesk-tight', 'condensed-stack', 'technical'],
		accents: ['measure-marks', 'blocks', 'bar-code', 'corner-ticks'],
		finishes: ['clean', 'matte', 'xerox'],
		cameras: ['still', 'push-in'],
		transitions: ['graphic-wipe', 'hard-cut', 'clock'],
		sfx: ['crisp', 'digital'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'bar', 'dashed'],
		titles: ['boxed', 'tag', 'cutout'],
		motion: ['slide-shutter', 'stagger-drop', 'slam'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['grotesk', 'condensed', 'sans'],
		bodyFontCategories: ['grotesk', 'mono', 'condensed'],
		palettes: ['mono', 'slate', 'arctic', 'azure'],
		arcs: ['index-cards', 'rapid-list', 'poster-series', 'data-story'],
	},
	'aurora-soft': {
		label: 'Aurora Soft',
		backgrounds: ['aurora', 'aurora-veil', 'gradient-mesh', 'soft-orbits'],
		layouts: ['centered', 'cover-stack', 'gutter-right'],
		typography: ['geometric-round', 'friendly', 'wide-track'],
		accents: ['halo', 'orbits', 'pills', 'none'],
		finishes: ['glass', 'bloom', 'clean'],
		cameras: ['drift', 'sway', 'pull-out'],
		transitions: ['dissolve', 'iris', 'card-flip'],
		sfx: ['minimal', 'organic'],
		textCase: ['title', 'sentence'],
		corners: ['pill', 'soft'],
		rules: ['gradient', 'none', 'thin'],
		titles: ['plate', 'ghost', 'stack'],
		motion: ['scale-fade', 'blur-in', 'rise'],
		tempo: [0.84, 0.88, 0.92],
		displayFontCategories: ['rounded', 'sans', 'grotesk'],
		bodyFontCategories: ['rounded', 'sans'],
		palettes: ['arctic', 'royal', 'azure', 'midnight'],
		arcs: ['reveal', 'explainer', 'product-tour', 'lookbook'],
	},
	'concrete-brut': {
		label: 'Concrete Brut',
		backgrounds: ['concrete-slab', 'editorial-slab', 'flat-field', 'stripe-march'],
		layouts: ['corner-anchor', 'baseline-drop', 'full-bleed'],
		typography: ['brutalist', 'stencil-industrial', 'wide-track'],
		accents: ['blocks', 'corner-ticks', 'measure-marks', 'bar-code'],
		finishes: ['matte', 'noir', 'xerox'],
		cameras: ['still', 'handheld', 'push-in'],
		transitions: ['hard-cut', 'graphic-wipe'],
		sfx: ['minimal', 'crisp'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['bar', 'none', 'ticked'],
		titles: ['cutout', 'stack', 'outline'],
		motion: ['slam', 'mask-reveal', 'slide-shutter'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['condensed', 'grotesk', 'display'],
		bodyFontCategories: ['grotesk', 'mono', 'condensed'],
		palettes: ['mono', 'slate', 'ember', 'midnight'],
		arcs: ['manifesto', 'thesis-proof', 'versus', 'hot-take'],
	},
	'holo-foil': {
		label: 'Holo Foil',
		backgrounds: ['holo-foil', 'liquid-chrome', 'kaleidoscope', 'gradient-mesh'],
		layouts: ['cover-stack', 'centered', 'pillar-center'],
		typography: ['display-swash', 'wide-track', 'geometric-round'],
		accents: ['orbits', 'halo', 'rings', 'starfield'],
		finishes: ['chrome', 'glass', 'bloom'],
		cameras: ['orbit', 'sway', 'push-in'],
		transitions: ['card-flip', 'iris', 'clock'],
		sfx: ['digital', 'cinematic'],
		textCase: ['upper', 'title'],
		corners: ['pill', 'soft'],
		rules: ['gradient', 'none'],
		titles: ['ghost', 'plate', 'shadowbox'],
		motion: ['spin-in', 'scale-fade', 'elastic'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['display', 'rounded', 'grotesk'],
		bodyFontCategories: ['rounded', 'grotesk', 'sans'],
		palettes: ['royal', 'neon', 'arctic', 'midnight'],
		arcs: ['product-tour', 'reveal', 'lookbook', 'hook-drop'],
	},
	'stencil-works': {
		label: 'Stencil Works',
		backgrounds: ['concrete-slab', 'drafting-wash', 'stripe-march', 'hex-scatter'],
		layouts: ['banner-top', 'corner-anchor', 'wide-stage'],
		typography: ['stencil-industrial', 'brutalist', 'condensed-stack'],
		accents: ['chevrons', 'bar-code', 'blocks', 'corner-ticks'],
		finishes: ['matte', 'print', 'xerox'],
		cameras: ['still', 'push-in', 'handheld'],
		transitions: ['graphic-wipe', 'hard-cut', 'directional'],
		sfx: ['crisp', 'minimal'],
		textCase: ['upper'],
		corners: ['sharp'],
		rules: ['ticked', 'bar', 'dashed'],
		titles: ['tag', 'cutout', 'boxed'],
		motion: ['slam', 'sweep', 'slide-shutter'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['condensed', 'display', 'tech'],
		bodyFontCategories: ['condensed', 'mono', 'grotesk'],
		palettes: ['ember', 'mono', 'slate', 'forest'],
		arcs: ['how-to', 'briefing', 'manifesto', 'diagnostic'],
	},
	'sticker-bomb': {
		label: 'Sticker Bomb',
		backgrounds: ['confetti-field', 'terrazzo', 'kaleidoscope', 'halftone-drift'],
		layouts: ['offset-stack', 'quadrant', 'corner-anchor'],
		typography: ['comic-punch', 'ransom-cut', 'display-swash'],
		accents: ['sparks', 'triangles', 'discs', 'starfield'],
		finishes: ['riso', 'clean', 'bloom'],
		cameras: ['sway', 'handheld'],
		transitions: ['punch-cut', 'kinetic', 'card-flip'],
		sfx: ['crisp', 'organic'],
		textCase: ['upper'],
		corners: ['pill'],
		rules: ['zigzag', 'dotted', 'bar'],
		titles: ['shadowbox', 'cutout', 'marquee'],
		motion: ['elastic', 'spin-in', 'stagger-drop'],
		tempo: [1.08, 1.12, 1.16],
		displayFontCategories: ['comic', 'display', 'retro'],
		bodyFontCategories: ['comic', 'rounded', 'sans'],
		palettes: ['neon', 'sunrise', 'ember', 'royal'],
		arcs: ['rapid-list', 'hot-take', 'hook-drop', 'scrapbook'],
	},
	'wireframe-lab': {
		label: 'Wireframe Lab',
		backgrounds: ['drafting-wash', 'trace-lines', 'iso-shards', 'crt-glow'],
		layouts: ['margin-note', 'quadrant', 'wide-stage'],
		typography: ['mono-terminal', 'technical', 'pixel-arcade'],
		accents: ['crosshair', 'measure-marks', 'hex-cluster', 'corner-ticks'],
		finishes: ['matte', 'neon', 'glass'],
		cameras: ['drift', 'orbit', 'still'],
		transitions: ['clock', 'directional', 'hard-cut'],
		sfx: ['digital', 'minimal'],
		textCase: ['upper', 'sentence'],
		corners: ['sharp'],
		rules: ['dashed', 'ticked', 'bracket'],
		titles: ['tag', 'bookend', 'outline'],
		motion: ['typewriter', 'mask-reveal', 'stagger-drop'],
		tempo: [0.96, 1, 1.04],
		displayFontCategories: ['mono', 'tech', 'pixel'],
		bodyFontCategories: ['mono', 'tech'],
		palettes: ['midnight', 'forest', 'azure', 'mono'],
		arcs: ['diagnostic', 'how-to', 'roadmap', 'explainer'],
	},
	'gradient-runway': {
		label: 'Gradient Runway',
		backgrounds: ['gradient-mesh', 'aurora', 'holo-foil', 'sunburst-rays'],
		layouts: ['baseline-drop', 'cover-stack', 'centered'],
		typography: ['wide-track', 'display-swash', 'grotesk-tight'],
		accents: ['waves', 'halo', 'pills', 'orbits'],
		finishes: ['bloom', 'glass', 'chrome'],
		cameras: ['dolly', 'push-in', 'sway'],
		transitions: ['directional', 'card-flip', 'punch-cut'],
		sfx: ['digital', 'cinematic'],
		textCase: ['upper', 'title'],
		corners: ['pill'],
		rules: ['gradient', 'bar', 'none'],
		titles: ['plate', 'marquee', 'ghost'],
		motion: ['sweep', 'zoom-punch', 'scale-fade'],
		tempo: [1, 1.04, 1.08],
		displayFontCategories: ['display', 'grotesk', 'rounded'],
		bodyFontCategories: ['grotesk', 'sans', 'rounded'],
		palettes: ['royal', 'neon', 'sunrise', 'midnight'],
		arcs: ['lookbook', 'product-tour', 'hook-drop', 'reveal'],
	},
	'micro-motion': {
		label: 'Micro Motion',
		backgrounds: ['flat-field', 'halftone-drift', 'soft-orbits', 'vertical-fade'],
		layouts: ['lower-third', 'margin-note', 'centered'],
		typography: ['grotesk-tight', 'geometric-round', 'technical'],
		accents: ['pills', 'none', 'corner-ticks', 'measure-marks'],
		finishes: ['clean', 'matte', 'glass'],
		cameras: ['still', 'drift'],
		transitions: ['dissolve', 'directional', 'card-flip'],
		sfx: ['minimal', 'digital'],
		textCase: ['title', 'sentence'],
		corners: ['pill', 'soft'],
		rules: ['thin', 'gradient', 'none'],
		titles: ['plate', 'inline', 'tag'],
		motion: ['rise', 'scale-fade', 'elastic'],
		tempo: [0.92, 0.96, 1],
		displayFontCategories: ['grotesk', 'sans', 'rounded'],
		bodyFontCategories: ['sans', 'grotesk', 'rounded'],
		palettes: ['arctic', 'mono', 'azure', 'paper'],
		arcs: ['product-tour', 'explainer', 'index-cards', 'how-to'],
	},
	'night-market': {
		label: 'Night Market',
		backgrounds: ['spotlight', 'nebula-drift', 'vhs-tracking', 'corner-glow'],
		layouts: ['full-bleed', 'lower-third', 'offset-stack'],
		typography: ['display-swash', 'condensed-stack', 'comic-punch'],
		accents: ['sparks', 'starfield', 'pills', 'halo'],
		finishes: ['neon', 'bloom', 'film'],
		cameras: ['handheld', 'drift', 'sway'],
		transitions: ['kinetic', 'punch-cut', 'hard-cut'],
		sfx: ['crisp', 'organic'],
		textCase: ['upper'],
		corners: ['pill', 'sharp'],
		rules: ['gradient', 'zigzag', 'ticked'],
		titles: ['marquee', 'shadowbox', 'tag'],
		motion: ['glitch', 'elastic', 'zoom-punch'],
		tempo: [1.04, 1.08, 1.12],
		displayFontCategories: ['display', 'retro', 'devanagari', 'condensed'],
		bodyFontCategories: ['sans', 'condensed', 'devanagari'],
		palettes: ['neon', 'ember', 'midnight', 'royal'],
		arcs: ['journey', 'hook-drop', 'rapid-list', 'lookbook'],
	},
} as const satisfies Record<string, TemplateRecipe>

export type TemplateId = keyof typeof TEMPLATE_KIT
export const TEMPLATE_IDS = Object.keys(TEMPLATE_KIT) as TemplateId[]
